### ISSUE TITLE
How to get structure specified in XML?

### ISSUE THREAD

**Issue by Kevin-free** [clbanning/mxj#100]
Hello~ I am tried to get structure specified in XML by this repo. But I'm having some difficulties, if you can help me I'd be very grateful! For details, please refer to the question I posted at the following link:

https://stackoverflow.com/questions/73290795/how-to-get-structure-specified-in-xml-with-go

**Comment by clbanning** [comment]
This package cannot do what you're trying to do - converting::
`<struct name="STRUCT_1">
    <entry name="ENTRY_1"/>
  </struct>`
into:
`map["STRUCT_1"] == ["ENTRY_1"]`.

It does syntactic conversion only and does not recognize any "semantic" labels, such as `name`.  

it will  convert
 `<struct name="STRUCT_1">
    <entry name="ENTRY_1"/>
  </struct>
`
into
`map[struct:map[-name:STRUCT_1 entry:map[-name:ENTRY_1]]]
`.

You'll have to provide the "semantic" logic to scan the map[string]interface{} value and create entries in a new map[string]string value where the keys are the values for the `name` attributes that are parsed by the package as map[string]interface{} values where the key is `-name`.

**Comment by Kevin-free** [comment]
> 



> This package cannot do what you're trying to do - converting:: `<struct name="STRUCT_1"> <entry name="ENTRY_1"/> </struct>` into: `map["STRUCT_1"] == ["ENTRY_1"]`.
> 
> It does syntactic conversion only and does not recognize any "semantic" labels, such as `name`.
> 
> it will convert `<struct name="STRUCT_1"> <entry name="ENTRY_1"/> </struct> ` into `map[struct:map[-name:STRUCT_1 entry:map[-name:ENTRY_1]]] `.
> 
> You'll have to provide the "semantic" logic to scan the map[string]interface{} value and create entries in a new map[string]string value where the keys are the values for the `name` attributes that are parsed by the package as map[string]interface{} values where the key is `-name`.

**Comment by Kevin-free** [comment]
> This package cannot do what you're trying to do - converting:: `<struct name="STRUCT_1"> <entry name="ENTRY_1"/> </struct>` into: `map["STRUCT_1"] == ["ENTRY_1"]`.
> 
> It does syntactic conversion only and does not recognize any "semantic" labels, such as `name`.
> 
> it will convert `<struct name="STRUCT_1"> <entry name="ENTRY_1"/> </struct> ` into `map[struct:map[-name:STRUCT_1 entry:map[-name:ENTRY_1]]] `.
> 
> You'll have to provide the "semantic" logic to scan the map[string]interface{} value and create entries in a new map[string]string value where the keys are the values for the `name` attributes that are parsed by the package as map[string]interface{} values where the key is `-name`.

Thanks! I solved this problem by another way.
