### ISSUE TITLE
Consider Exposing MapSeq Sort Functionality

### ISSUE THREAD

**Issue by davidkrauser** [clbanning/mxj#101]
First off - I just want to say thank you for this library. I appreciate all of the time you put into writing and maintaining it :slightly_smiling_face:

----

I'm currently using `mxj` to extract data from an XML file, modify that XML file, then write it back. For my use-case, order is important, so I've been using the `MapSeq` structure.

In some cases, I need to take a set of nodes and parse them into an ordered list of Golang objects for manipulation. `mxj` has some nice facilities for ordering `MapSeq` data, but they are not exported for use by the library-user: https://github.com/clbanning/mxj/blob/c77d66e12fb2934037995f87b7fe7c0f48b87cb4/xmlseq.go#L828-L865

Would you consider exporting some of that functionality? I can propose a PR if you are open to the idea. Or if you'd rather do it your own way, that's fine, too :slightly_smiling_face:

Additionally, it may also be useful to expose some methods that make it easy to convert a map into a list of `keyval` structs for sorting.

**Comment by clbanning** [comment]
See Comment on Issue #102.

**Comment by davidkrauser** [comment]
I'll close this in favor of #102 :slightly_smiling_face:
