### ISSUE TITLE
Sequence not being observed when converting from XML to JSON

### ISSUE THREAD

**Issue by mmussett** [clbanning/mxj#108]
Firstly, thanks for this cool library. It fits perfectly for my needs; however i've come a across an issue.

The ordering is incorrectly being generated for XML. You can see the actual order of elements follows:

Envelope->Body->OrderCreateRQ->Document|Party|Query

But the actual sequence generated when i covert back from sequenced JSON to XML follows:

Envelope->Body->OrderCreateRQ->Query|Party|Document

It appears the sequence is correct in the JSON being generated, so it looks to be a defect in the XmlSeq() method.

**Input  XML   :**  

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:get="http://www.iata.org/IATA/EDIST/2017.2"><soapenv:Body><OrderCreateRQ xmlns="http://www.iata.org/IATA/EDIST/2017.2" Version="17.2" PrimaryLangID="EN" AltLangID="EN"><Document><Name>BA</Name></Document><Party><Sender><CorporateSender><ID>JB000000</ID></CorporateSender></Sender><Participants><Participant><TravelAgencyParticipant SequenceNumber="1"><Contacts><Contact><EmailContact><Address>agent.email@xyz.com</Address></EmailContact></Contact></Contacts><IATA_Number>00000000</IATA_Number><AgencyID>Test_Agency</AgencyID></TravelAgencyParticipant></Participant></Participants></Party><Query><Order><Offer OfferID="OF-44a450e6-75b3-4443-9c18-1024137b082f" Owner="BA" ResponseID="tx-08-201-0d5cafdd-ea25-48ac-9a3b-42480defcad4"><OfferItem OfferItemID="OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-1"><PassengerRefs>SH1 SH2 SH3</PassengerRefs></OfferItem><OfferItem OfferItemID="OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-2"><PassengerRefs>SH4 SH5</PassengerRefs></OfferItem><OfferItem OfferItemID="OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-3"><PassengerRefs>SH6 SH7</PassengerRefs></OfferItem><OfferItem OfferItemID="OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-4"><PassengerRefs>SH8 SH9</PassengerRefs></OfferItem></Offer></Order><Payments><Payment><Type>CC</Type><Method><PaymentCard><CardCode>MD</CardCode><CardNumber>7777884566565720</CardNumber><SeriesCode>123</SeriesCode><CardHolderName>MR MIKE TEST</CardHolderName><CardHolderBillingAddress><Street>Beeches Apartment</Street><Street>200 Lampton Road</Street><CityName>LON</CityName><PostalCode>TW345RT</PostalCode><CountryCode>GB</CountryCode></CardHolderBillingAddress><Surcharge><Amount Code="GBP">0.00</Amount></Surcharge><EffectiveExpireDate><Effective>1212</Effective><Expiration>0219</Expiration></EffectiveExpireDate></PaymentCard></Method><Amount Code="GBP">528.70</Amount><Payer><ContactInfoRefs>Payer</ContactInfoRefs></Payer></Payment></Payments><DataLists><PassengerList><Passenger PassengerID="SH1"><PTC>ADT</PTC><Individual><Birthdate>1982-12-15</Birthdate><Gender>Male</Gender><NameTitle>DR</NameTitle><GivenName>one</GivenName><Surname>TEST</Surname></Individual><ContactInfoRef>ContactInfo-SH1</ContactInfoRef></Passenger><Passenger PassengerID="SH2"><PTC>ADT</PTC><Individual><Birthdate>1983-08-05</Birthdate><Gender>Male</Gender><NameTitle>DR</NameTitle><GivenName>TWO</GivenName><Surname>TEST</Surname></Individual><InfantRef>SH9</InfantRef></Passenger><Passenger PassengerID="SH3"><PTC>ADT</PTC><Individual><Birthdate>1984-12-15</Birthdate><Gender>Male</Gender><NameTitle>MR</NameTitle><GivenName>three</GivenName><Surname>TEST</Surname></Individual><InfantRef>SH8</InfantRef></Passenger><Passenger PassengerID="SH4"><PTC>ADT</PTC><Individual><Birthdate>2005-10-15</Birthdate><Gender>Male</Gender><NameTitle>MR</NameTitle><GivenName>four</GivenName><Surname>TEST</Surname></Individual></Passenger><Passenger PassengerID="SH5"><PTC>ADT</PTC><Individual><Birthdate>2005-12-15</Birthdate><Gender>Male</Gender><NameTitle>MR</NameTitle><GivenName>five</GivenName><Surname>TEST</Surname></Individual></Passenger><Passenger PassengerID="SH6"><PTC>CHD</PTC><Individual><Birthdate>2010-12-15</Birthdate><Gender>Male</Gender><NameTitle>MR</NameTitle><GivenName>six</GivenName><Surname>TEST</Surname></Individual></Passenger><Passenger PassengerID="SH7"><PTC>CHD</PTC><Individual><Birthdate>2012-12-15</Birthdate><Gender>Male</Gender><NameTitle>MR</NameTitle><GivenName>seven</GivenName><Surname>TEST</Surname></Individual></Passenger><Passenger PassengerID="SH8"><PTC>INF</PTC><Individual><Birthdate>2017-12-15</Birthdate><Gender>Male</Gender><NameTitle>MR</NameTitle><GivenName>eight</GivenName><Surname>TEST</Surname></Individual></Passenger><Passenger PassengerID="SH9"><PTC>INF</PTC><Individual><Birthdate>2017-10-15</Birthdate><Gender>Male</Gender><NameTitle>MR</NameTitle><GivenName>nine</GivenName><Surname>TEST</Surname></Individual></Passenger></PassengerList><ContactList><ContactInformation ContactID="ContactInfo-SH1"><!--ContactType>Payment</ContactType--><ContactProvided><EmailAddress><EmailAddressValue>CBD.DBA@BA.COM</EmailAddressValue></EmailAddress></ContactProvided><ContactProvided><Phone><Label>mobile</Label><CountryDialingCode>11</CountryDialingCode><AreaCode>44</AreaCode><PhoneNumber>11122211</PhoneNumber></Phone></ContactProvided></ContactInformation><ContactInformation ContactID="Payer"><ContactType>Payment</ContactType><ContactProvided><EmailAddress><EmailAddressValue>third.party@xyz.com</EmailAddressValue></EmailAddress></ContactProvided><ContactProvided><Phone><Label>mobile</Label><CountryDialingCode>11</CountryDialingCode><AreaCode>44</AreaCode><PhoneNumber>888444444</PhoneNumber></Phone></ContactProvided><Individual><NameTitle>Mr</NameTitle><GivenName>MIKE</GivenName><Surname>TEST</Surname></Individual></ContactInformation></ContactList></DataLists></Query></OrderCreateRQ></soapenv:Body></soapenv:Envelope>`

**Output   Sequenced JSON:**  

`{"soapenv:Envelope":{"#attr":{"xmlns:get":{"#seq":1,"#text":"http://www.iata.org/IATA/EDIST/2017.2"},"xmlns:soapenv":{"#seq":0,"#text":"http://schemas.xmlsoap.org/soap/envelope/"}},"soapenv:Body":{"#seq":0,"OrderCreateRQ":{"#attr":{"AltLangID":{"#seq":3,"#text":"EN"},"PrimaryLangID":{"#seq":2,"#text":"EN"},"Version":{"#seq":1,"#text":17.2},"xmlns":{"#seq":0,"#text":"http://www.iata.org/IATA/EDIST/2017.2"}},"#seq":0,"Document":{"#seq":0,"Name":{"#seq":0,"#text":"BA"}},"Party":{"#seq":1,"Participants":{"#seq":1,"Participant":{"#seq":0,"TravelAgencyParticipant":{"#attr":{"SequenceNumber":{"#seq":0,"#text":1}},"#seq":0,"AgencyID":{"#seq":2,"#text":"Test_Agency"},"Contacts":{"#seq":0,"Contact":{"#seq":0,"EmailContact":{"#seq":0,"Address":{"#seq":0,"#text":"agent.email@xyz.com"}}}},"IATA_Number":{"#seq":1,"#text":0}}}},"Sender":{"#seq":0,"CorporateSender":{"#seq":0,"ID":{"#seq":0,"#text":"JB000000"}}}},"Query":{"#seq":2,"DataLists":{"#seq":2,"ContactList":{"#seq":1,"ContactInformation":[{"#attr":{"ContactID":{"#seq":0,"#text":"ContactInfo-SH1"}},"#comment":{"#seq":0,"#text":"ContactType\u003ePayment\u003c/ContactType"},"#seq":0,"ContactProvided":[{"#seq":1,"EmailAddress":{"#seq":0,"EmailAddressValue":{"#seq":0,"#text":"CBD.DBA@BA.COM"}}},{"#seq":2,"Phone":{"#seq":0,"AreaCode":{"#seq":2,"#text":44},"CountryDialingCode":{"#seq":1,"#text":11},"Label":{"#seq":0,"#text":"mobile"},"PhoneNumber":{"#seq":3,"#text":11122211}}}]},{"#attr":{"ContactID":{"#seq":0,"#text":"Payer"}},"#seq":1,"ContactProvided":[{"#seq":1,"EmailAddress":{"#seq":0,"EmailAddressValue":{"#seq":0,"#text":"third.party@xyz.com"}}},{"#seq":2,"Phone":{"#seq":0,"AreaCode":{"#seq":2,"#text":44},"CountryDialingCode":{"#seq":1,"#text":11},"Label":{"#seq":0,"#text":"mobile"},"PhoneNumber":{"#seq":3,"#text":888444444}}}],"ContactType":{"#seq":0,"#text":"Payment"},"Individual":{"#seq":3,"GivenName":{"#seq":1,"#text":"MIKE"},"NameTitle":{"#seq":0,"#text":"Mr"},"Surname":{"#seq":2,"#text":"TEST"}}}]},"PassengerList":{"#seq":0,"Passenger":[{"#attr":{"PassengerID":{"#seq":0,"#text":"SH1"}},"#seq":0,"ContactInfoRef":{"#seq":2,"#text":"ContactInfo-SH1"},"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"1982-12-15"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"one"},"NameTitle":{"#seq":2,"#text":"DR"},"Surname":{"#seq":4,"#text":"TEST"}},"PTC":{"#seq":0,"#text":"ADT"}},{"#attr":{"PassengerID":{"#seq":0,"#text":"SH2"}},"#seq":1,"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"1983-08-05"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"TWO"},"NameTitle":{"#seq":2,"#text":"DR"},"Surname":{"#seq":4,"#text":"TEST"}},"InfantRef":{"#seq":2,"#text":"SH9"},"PTC":{"#seq":0,"#text":"ADT"}},{"#attr":{"PassengerID":{"#seq":0,"#text":"SH3"}},"#seq":2,"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"1984-12-15"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"three"},"NameTitle":{"#seq":2,"#text":"MR"},"Surname":{"#seq":4,"#text":"TEST"}},"InfantRef":{"#seq":2,"#text":"SH8"},"PTC":{"#seq":0,"#text":"ADT"}},{"#attr":{"PassengerID":{"#seq":0,"#text":"SH4"}},"#seq":3,"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"2005-10-15"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"four"},"NameTitle":{"#seq":2,"#text":"MR"},"Surname":{"#seq":4,"#text":"TEST"}},"PTC":{"#seq":0,"#text":"ADT"}},{"#attr":{"PassengerID":{"#seq":0,"#text":"SH5"}},"#seq":4,"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"2005-12-15"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"five"},"NameTitle":{"#seq":2,"#text":"MR"},"Surname":{"#seq":4,"#text":"TEST"}},"PTC":{"#seq":0,"#text":"ADT"}},{"#attr":{"PassengerID":{"#seq":0,"#text":"SH6"}},"#seq":5,"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"2010-12-15"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"six"},"NameTitle":{"#seq":2,"#text":"MR"},"Surname":{"#seq":4,"#text":"TEST"}},"PTC":{"#seq":0,"#text":"CHD"}},{"#attr":{"PassengerID":{"#seq":0,"#text":"SH7"}},"#seq":6,"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"2012-12-15"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"seven"},"NameTitle":{"#seq":2,"#text":"MR"},"Surname":{"#seq":4,"#text":"TEST"}},"PTC":{"#seq":0,"#text":"CHD"}},{"#attr":{"PassengerID":{"#seq":0,"#text":"SH8"}},"#seq":7,"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"2017-12-15"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"eight"},"NameTitle":{"#seq":2,"#text":"MR"},"Surname":{"#seq":4,"#text":"TEST"}},"PTC":{"#seq":0,"#text":"INF"}},{"#attr":{"PassengerID":{"#seq":0,"#text":"SH9"}},"#seq":8,"Individual":{"#seq":1,"Birthdate":{"#seq":0,"#text":"2017-10-15"},"Gender":{"#seq":1,"#text":"Male"},"GivenName":{"#seq":3,"#text":"nine"},"NameTitle":{"#seq":2,"#text":"MR"},"Surname":{"#seq":4,"#text":"TEST"}},"PTC":{"#seq":0,"#text":"INF"}}]}},"Order":{"#seq":0,"Offer":{"#attr":{"OfferID":{"#seq":0,"#text":"OF-44a450e6-75b3-4443-9c18-1024137b082f"},"Owner":{"#seq":1,"#text":"BA"},"ResponseID":{"#seq":2,"#text":"tx-08-201-0d5cafdd-ea25-48ac-9a3b-42480defcad4"}},"#seq":0,"OfferItem":[{"#attr":{"OfferItemID":{"#seq":0,"#text":"OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-1"}},"#seq":0,"PassengerRefs":{"#seq":0,"#text":"SH1 SH2 SH3"}},{"#attr":{"OfferItemID":{"#seq":0,"#text":"OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-2"}},"#seq":1,"PassengerRefs":{"#seq":0,"#text":"SH4 SH5"}},{"#attr":{"OfferItemID":{"#seq":0,"#text":"OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-3"}},"#seq":2,"PassengerRefs":{"#seq":0,"#text":"SH6 SH7"}},{"#attr":{"OfferItemID":{"#seq":0,"#text":"OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-4"}},"#seq":3,"PassengerRefs":{"#seq":0,"#text":"SH8 SH9"}}]}},"Payments":{"#seq":1,"Payment":{"#seq":0,"Amount":{"#attr":{"Code":{"#seq":0,"#text":"GBP"}},"#seq":2,"#text":528.7},"Method":{"#seq":1,"PaymentCard":{"#seq":0,"CardCode":{"#seq":0,"#text":"MD"},"CardHolderBillingAddress":{"#seq":4,"CityName":{"#seq":2,"#text":"LON"},"CountryCode":{"#seq":4,"#text":"GB"},"PostalCode":{"#seq":3,"#text":"TW345RT"},"Street":[{"#seq":0,"#text":"Beeches Apartment"},{"#seq":1,"#text":"200 Lampton Road"}]},"CardHolderName":{"#seq":3,"#text":"MR MIKE TEST"},"CardNumber":{"#seq":1,"#text":7777884566565720},"EffectiveExpireDate":{"#seq":6,"Effective":{"#seq":0,"#text":1212},"Expiration":{"#seq":1,"#text":219}},"SeriesCode":{"#seq":2,"#text":123},"Surcharge":{"#seq":5,"Amount":{"#attr":{"Code":{"#seq":0,"#text":"GBP"}},"#seq":0,"#text":0}}}},"Payer":{"#seq":3,"ContactInfoRefs":{"#seq":0,"#text":"Payer"}},"Type":{"#seq":0,"#text":"CC"}}}}}}}}`

**Inverse Operation  :**  

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:get="http://www.iata.org/IATA/EDIST/2017.2"><soapenv:Body><OrderCreateRQ xmlns="http://www.iata.org/IATA/EDIST/2017.2" Version="17.2" PrimaryLangID="EN" AltLangID="EN"><Query><Payments><Payment><Type>CC</Type><Payer><ContactInfoRefs>Payer</ContactInfoRefs></Payer><Method><PaymentCard><CardHolderName>MR MIKE TEST</CardHolderName><CardHolderBillingAddress><Street>200 Lampton Road</Street><Street>Beeches Apartment</Street><PostalCode>TW345RT</PostalCode><CountryCode>GB</CountryCode><CityName>LON</CityName></CardHolderBillingAddress><CardCode>MD</CardCode><Surcharge><Amount Code="GBP"/></Surcharge><SeriesCode/><EffectiveExpireDate><Expiration/><Effective/></EffectiveExpireDate><CardNumber/></PaymentCard></Method><Amount Code="GBP"/></Payment></Payments><Order><Offer OfferID="OF-44a450e6-75b3-4443-9c18-1024137b082f" ResponseID="tx-08-201-0d5cafdd-ea25-48ac-9a3b-42480defcad4" Owner="BA"><OfferItem OfferItemID="OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-4"><PassengerRefs>SH8 SH9</PassengerRefs></OfferItem><OfferItem OfferItemID="OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-3"><PassengerRefs>SH6 SH7</PassengerRefs></OfferItem><OfferItem OfferItemID="OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-2"><PassengerRefs>SH4 SH5</PassengerRefs></OfferItem><OfferItem OfferItemID="OF-44a450e6-75b3-4443-9c18-1024137b082f-OI-1"><PassengerRefs>SH1 SH2 SH3</PassengerRefs></OfferItem></Offer></Order><DataLists><PassengerList><Passenger PassengerID="SH9"><Individual><GivenName>nine</GivenName><Gender>Male</Gender><Birthdate>2017-10-15</Birthdate><Surname>TEST</Surname><NameTitle>MR</NameTitle></Individual><PTC>INF</PTC></Passenger><Passenger PassengerID="SH8"><PTC>INF</PTC><Individual><NameTitle>MR</NameTitle><GivenName>eight</GivenName><Gender>Male</Gender><Birthdate>2017-12-15</Birthdate><Surname>TEST</Surname></Individual></Passenger><Passenger PassengerID="SH7"><PTC>CHD</PTC><Individual><Surname>TEST</Surname><NameTitle>MR</NameTitle><GivenName>seven</GivenName><Gender>Male</Gender><Birthdate>2012-12-15</Birthdate></Individual></Passenger><Passenger PassengerID="SH6"><PTC>CHD</PTC><Individual><Gender>Male</Gender><Birthdate>2010-12-15</Birthdate><Surname>TEST</Surname><NameTitle>MR</NameTitle><GivenName>six</GivenName></Individual></Passenger><Passenger PassengerID="SH5"><PTC>ADT</PTC><Individual><Surname>TEST</Surname><NameTitle>MR</NameTitle><GivenName>five</GivenName><Gender>Male</Gender><Birthdate>2005-12-15</Birthdate></Individual></Passenger><Passenger PassengerID="SH4"><PTC>ADT</PTC><Individual><Surname>TEST</Surname><NameTitle>MR</NameTitle><GivenName>four</GivenName><Gender>Male</Gender><Birthdate>2005-10-15</Birthdate></Individual></Passenger><Passenger PassengerID="SH3"><InfantRef>SH8</InfantRef><Individual><Surname>TEST</Surname><NameTitle>MR</NameTitle><GivenName>three</GivenName><Gender>Male</Gender><Birthdate>1984-12-15</Birthdate></Individual><PTC>ADT</PTC></Passenger><Passenger PassengerID="SH2"><PTC>ADT</PTC><InfantRef>SH9</InfantRef><Individual><Surname>TEST</Surname><NameTitle>DR</NameTitle><GivenName>TWO</GivenName><Gender>Male</Gender><Birthdate>1983-08-05</Birthdate></Individual></Passenger><Passenger PassengerID="SH1"><PTC>ADT</PTC><Individual><Surname>TEST</Surname><NameTitle>DR</NameTitle><GivenName>one</GivenName><Gender>Male</Gender><Birthdate>1982-12-15</Birthdate></Individual><ContactInfoRef>ContactInfo-SH1</ContactInfoRef></Passenger></PassengerList><ContactList><ContactInformation ContactID="Payer"><Individual><Surname>TEST</Surname><NameTitle>Mr</NameTitle><GivenName>MIKE</GivenName></Individual><ContactType>Payment</ContactType><ContactProvided><Phone><PhoneNumber/><Label>mobile</Label><CountryDialingCode/><AreaCode/></Phone></ContactProvided><ContactProvided><EmailAddress><EmailAddressValue>third.party@xyz.com</EmailAddressValue></EmailAddress></ContactProvided></ContactInformation><ContactInformation ContactID="ContactInfo-SH1"><ContactProvided><Phone><PhoneNumber/><Label>mobile</Label><CountryDialingCode/><AreaCode/></Phone></ContactProvided><ContactProvided><EmailAddress><EmailAddressValue>CBD.DBA@BA.COM</EmailAddressValue></EmailAddress></ContactProvided><!--ContactType>Payment</ContactType--></ContactInformation></ContactList></DataLists></Query><Party><Participants><Participant><TravelAgencyParticipant SequenceNumber="1"><Contacts><Contact><EmailContact><Address>agent.email@xyz.com</Address></EmailContact></Contact></Contacts><AgencyID>Test_Agency</AgencyID><IATA_Number/></TravelAgencyParticipant></Participant></Participants><Sender><CorporateSender><ID>JB000000</ID></CorporateSender></Sender></Party><Document><Name>BA</Name></Document></OrderCreateRQ></soapenv:Body></soapenv:Envelope>`

**Comment by clbanning** [comment]
I'll look into this when I get some time.  

Can you post the actual code you're using to generate the JSON and the re-marshaled XML.  

Also, is the JSON value what you expect?  Is it manipulated at all prior to re-marshaling to XML?  If not, why are you converting to JSON and then back to XML?

**Comment by mmussett** [comment]
JSON looks correct when generated i.e. sequence is observed on the elements I've checked.

I'm not manipulating the JSON to what's being generated from x2j before doing j2x inverse to check i don't break the XML against the schema definition.

I'm using your library to be able to process XML content in an processing pipeline project that expects everything to be represented in json during processing activity steps. At the end i need to squirt out schema valid XML.

**Comment by mmussett** [comment]
To convert from XML to JSON i'm using:

	msv, err := mxj.NewMapXmlSeq([]byte(xmldata), true)
	# wrapped your marshal
        json, err := json.Marshal(msv)

Inverse:

	mv, err := mxj.NewMapJson([]byte(jsondata))
        mv.Json(true)
        xml, err = mv.Xml()

**Comment by clbanning** [comment]
`mxj.NewMapJson` returns a value of type `mxj.Map` not `mxj.MapSeq`.  So the `mv.Xml()` call doesn't process the `#seq` keys in the map as indexes for ordering the (sub-)elements in the XML.  Try something like:

   msv = mxj.MapSeq(mv)
   xml, err := msv.Xml()

**Comment by mmussett** [comment]
I don't see a MapSeq() public func.

**Comment by mmussett** [comment]
Yes, realised should have been a cast. That worked... thanks!!!!

	mv, err := mxj.NewMapJson([]byte(jsondata))
	mv.Json(true)

	if err != nil {
		return false, err
	}

	var xml []byte
	if input.Ordered {
		msv := mxj.MapSeq(mv)
		xml, err = msv.Xml()
		if err != nil {
			return false, err
		}

	} else {
		xml, err = mv.Xml()
		if err != nil {
			return false, err
		}

	}

**Comment by mmussett** [comment]
Really appreciate the work you've done here. This stuff is super!

**Comment by clbanning** [comment]
In C we say "cast," but in Go we say "conversion,"
