### ISSUE TITLE
Any plans to support XInclude?

### ISSUE THREAD

**Issue by osxtest** [clbanning/mxj#115]
The current parse result looks like will trim the prefix of xinclude content, for instance:
- `<xi:include` tag will become `<include`
- `xmlns:xi=` attribute will become `xi=`

```go
func TestXInclude(t *testing.T) {
	data := []byte(`
<?xml version='1.0'?>
<document xmlns:xi="http://www.w3.org/2001/XInclude">
  <p>This document has been accessed
  <xi:include href="count.txt" parse="text"/> times.</p>
</document>`)

	m, err := mxj.NewMapXml(data)
	if err != nil {
		t.Fatal(err)
	}

	xml, err := m.Xml()
	if err != nil {
		t.Fatal(err)
	}
	println(string(xml))
}
```

output
```xml
<document xi="http://www.w3.org/2001/XInclude"><p>This document has been accessed<include href="count.txt" parse="text"/></p></document>
```

**Comment by clbanning** [comment]
Map values are created using the stdlib "encoding/xml" Decoder.  The "xi" name space is identified as "http://www.w3.org/2001/XInclude" in the xml.Name.Space element, but there's no clean way right now to carry that information with the Map value to include in the mxj.Map.Xml logic.  I'll give it some thought, however.

**Comment by clbanning** [comment]
Nope.
