### ISSUE TITLE
unable to convert []map[string]interface{} to xml , got UNKNOWN

### ISSUE THREAD

**Issue by zhangmk5** [clbanning/mxj#117]
when I try to convert map[string]interface{} to xml
![image](https://github.com/clbanning/mxj/assets/113656896/9f881ecb-a6d5-4fc1-8444-e6b3a325f383)
got error result
![image](https://github.com/clbanning/mxj/assets/113656896/378d70eb-bb6a-4f26-867a-a3fa6a7994cd)

**Comment by clbanning** [comment]
`map[interface{}]interface{}` types are not support, just as for encoding/json `Marshal` function in the standard library.
