### ISSUE TITLE
items.item[0].props.prop[0].name will result unexpected return value

### ISSUE THREAD

**Issue by t-rase** [clbanning/mxj#118]
Accessing the below structure with ValuesForPath("items.item[0].props.prop[0].name will result in a return map not only including the node Color but all items as well

e.g.
[0]map[string]interface{} item(id:1 ...
[1]map[string]interface{} item(id:2 ...
[2]map[string]interface{} item(id:3 ...
[4]interface{}string Color

i would expect only the color attribute to be returned since item accessing a defined value within the structure  

`<items>
	<item>
		<id>1</id>
		<date>20240101</date>
		<props>
			<prop>
				<name>Color</name>
				<value>Green</value>
			</prop>
		</props>
	</item>
	<item>
		<id>2</id>
		<date>20240101</date>
		<props>
			<prop>
				<name>Color</name>
				<value>Blue</value>
			</prop>
		</props>
	</item>
	<item>
		<id>3</id>
		<date>20240101</date>
		<props>
			<prop>
				<name>Color</name>
				<value>Red</value>
			</prop>
		</props>
	</item>
</items>`

**Comment by clbanning** [comment]
Please post code that recreates the issue.

**Comment by t-rase** [comment]
find an example below. i recommand adding multiple prop tags to each in the example  

`	indata, _ := os.ReadFile("example.xml")

	inputMap, _ = mxj.NewMapXml(indata)

	items, _ := inputMap.ValuesForPath("items.*")

	for i, _ := range items {
		props, _ := inputMap.ValuesForPath("items.item[" + strconv.Itoa(i) + "].props.prop")

		for j, _ := range props {
			searchstringbad := "items.item[" + strconv.Itoa(i) + "].props.prop[" + strconv.Itoa(j) + "]" //gives items and actual prop -> this is what i want minus the items
			searchstring := "items.item[" + strconv.Itoa(i) + "].props[" + strconv.Itoa(j) + "].prop"    //gives all props
			badoneprop, _ := inputMap.ValuesForPath(searchstringbad)
			oneprop, _ := inputMap.ValuesForPath(searchstring)

			println(len(badoneprop))
			println(len(oneprop))
		}

	}`

example needs to be remaned to xml
[example.txt](https://github.com/clbanning/mxj/files/14445550/example.txt)

**Comment by clbanning** [comment]
Does the following do what you want?

`
package main

import (
	"fmt"

	"github.com/clbanning/mxj"
)

var indata = []byte(`<items>
  <item>
    <id>1</id>
    <date>20240101</date>
    <props>
      <prop>
        <name>Color</name>
        <value>Green</value>
      </prop>
      <prop>
        <name>Height</name>
        <value>100</value>
      </prop>
    </props>
  </item>
  <item>
    <id>2</id>
    <date>20240101</date>
    <props>
      <prop>
        <name>Color</name>
        <value>Blue</value>
      </prop>
      <prop>
        <name>Height</name>
        <value>200</value>
      </prop>
    </props>
  </item>
  <item>
    <id>3</id>
    <date>20240101</date>
    <props>
      <prop>
        <name>Color</name>
        <value>Red</value>
      </prop>
    </props>
  </item>
</items>`)

func main() {
	// indata, _ := os.ReadFile("example.xml")
	inputMap, _ := mxj.NewMapXml(indata)
	println("\n", inputMap.StringIndent(), "\n")

	// just a test of retrieving "Color" values
	clb_prop, _ := inputMap.ValuesForKey("prop")
	fmt.Printf("%#v\n\n", clb_prop)

	for index, val := range clb_prop {
		clb_key, ok := val.(map[string]interface{})["name"]
		if !ok {
			continue
		}
		if clb_key == "Color" {
			fmt.Println("index:", index, "value:", val.(map[string]interface{})["value"])
		}
	}
}
`

**Comment by t-rase** [comment]
no this was just an example to recreate the issue of returning unwanted rows. In my real case i dont know the any of the values and try to map them accordingly. e.g. the props for each item could be different therefore i want to get each prop per item and check for exsistance. getting all props at onces will lose the Item parent relation

**Comment by clbanning** [comment]
Here's an example of pulling "props.prop" values with associated "id" and "date" values.

`package main

import (
	"fmt"

	"github.com/clbanning/mxj"
)

var indata = []byte(`<items>
  <item>
    <id>1</id>
    <date>20240101</date>
    <props>
      <prop>
        <name>Color</name>
        <value>Green</value>
      </prop>
      <prop>
        <name>Height</name>
        <value>100</value>
      </prop>
    </props>
  </item>
  <item>
    <id>2</id>
    <date>20240101</date>
    <props>
      <prop>
        <name>Color</name>
        <value>Blue</value>
      </prop>
      <prop>
        <name>Height</name>
        <value>200</value>
      </prop>
    </props>
  </item>
  <item>
    <id>3</id>
    <date>20240101</date>
    <props>
      <prop>
        <name>Color</name>
        <value>Red</value>
      </prop>
    </props>
  </item>
</items>`)

func main() {
	// indata, _ := os.ReadFile("example.xml")
	inputMap, _ := mxj.NewMapXml(indata)
	println("\n", inputMap.StringIndent(), "\n")

	// just a test of etrieving "Color" values along with "id" and "date" value
	clb_item, _ := inputMap.ValuesForKey("item")
	fmt.Printf("\nclb_item: %#v\n\n", clb_item)

	for _, v := range clb_item {
		fmt.Println("\nid:", v.(map[string]interface{})["id"], "date:", v.(map[string]interface{})["date"])

		// by mxj - grab the "prop" value
		val, err := mxj.Map(v.(map[string]interface{})).ValuesForPath("props.prop")
		if err != nil {
			fmt.Println("ValuesForPath err:", err)
		}
		fmt.Printf("props.prop: %#v\n", val)
	}
}`

**Comment by t-rase** [comment]
didnt get time to validate your approach but looks promising. still the original case should not happen in my point of view
