### ISSUE TITLE
All XML elements are unmarshalled with quotes as strings

### ISSUE THREAD

**Issue by sorenhoyer** [clbanning/mxj#12]
I don't know if this is the intended behavior, but mxj.NewMapXml() seem to unmarshal all XML elements to a string. In my case I'd have expected at least integers and bool values to be unmarshalled without quotes.

Here's an example to help illustrate the problem: http://play.golang.org/p/ZhGqn4EWHD

Otherwise I like this package, and perhaps I'll do a fork to implement this functionality, if it's not already there (undocumented) - it should be fairly easy to decide if the value is a string, int or bool, and for other types we would even add an attribute on the element to check against.

Again I don't know if this functionality is left out intentionally since perhaps you do not consider this a responsibility for this package, but something we should handle in our own code?

**Comment by mrsln** [comment]
I don't think the functionality implemented.
My workaround is to use mxj for parsing xml and correcting the data, then I get JSON and umarshaling it to  my structure.

```
  myMap, _ := mxj.NewMapXml(myXml)
  // fixing it by updating values, adding new structures
  myJson, _ := myMap.Json()
  
  var myStruct myConcreteStructure
  json.Unmarshal(myJson, &myStruct) // import "encoding/json"
```

**Comment by sorenhoyer** [comment]
Thanks mrln for your answer, but In my case I have no concrete structure, it is truly flexible. Right now I have to use reflection to iterate the interfaces inside the map and manually cast the values inside the decoded map to their appropiate type. This is all because all xml values gets stored in the map like: myMap["myBool"] = "false", myMap["myInt"] = "1337" instead of leaving out the quotes in these cases.

**Comment by sorenhoyer** [comment]
Sweet - Actually this feature is implemented already. I just noticed in https://github.com/clbanning/mxj/blob/master/xml.go#L50 it says:

"If the optional argument 'cast' is 'true', then values will be converted to boolean or float64 if possible." 

Closing this. :-)

**Comment by clbanning** [comment]
m, err := mxi.NewMapXml(xml_doc, true) will coerce values to bool/float64 if possible just like the stdlib json.Unmarshal() does when unmarshaling a JSON object to map[string]interface{}.  There is no attempt to interpret numeric values as int, etc.  It is intended to mimic json.Unmarshal().
