### ISSUE TITLE
github.com/clbanning/mxj/examples/gonuts9.go:8:2: cannot find package "tamgroup/mxj"

### ISSUE THREAD

**Issue by robmurtha** [clbanning/mxj#13]
the above error happens with go get on projects that include clbanning/mxj

also:
github.com/clbanning/mxj/examples
github.com/clbanning/mxj/examples/getmetrics1.go:47: main redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/books.go:36
github.com/clbanning/mxj/examples/getmetrics2.go:48: main redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/getmetrics1.go:47
github.com/clbanning/mxj/examples/getmetrics3.go:49: main redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/getmetrics2.go:48
github.com/clbanning/mxj/examples/getmetrics4.go:50: main redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/getmetrics3.go:49
github.com/clbanning/mxj/examples/gonuts1.go:39: main redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/getmetrics4.go:50
github.com/clbanning/mxj/examples/gonuts1a.go:26: msg1 redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/gonuts1.go:26
github.com/clbanning/mxj/examples/gonuts1a.go:37: msg2 redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/gonuts1.go:37
github.com/clbanning/mxj/examples/gonuts1a.go:39: main redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/gonuts1.go:39
github.com/clbanning/mxj/examples/gonuts2.go:62: main redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/gonuts1a.go:39
github.com/clbanning/mxj/examples/gonuts3.go:24: xmldata redeclared in this block
	previous declaration at github.com/clbanning/mxj/examples/books.go:34
github.com/clbanning/mxj/examples/gonuts3.go:24: too many errors

**Comment by clbanning** [comment]
thanks.  it should be "github.com/clbanning/mxj

**Comment by clbanning** [comment]
run the examples as: go run gonuts1.go
or: 
    go build gonuts1.go
    ./gonuts1
