### ISSUE TITLE
NewMapXmlSeq process instructions

### ISSUE THREAD

**Issue by s850042002** [clbanning/mxj#17]
hi,

I'm dealing with some XML files that have `<?xml version="1.0" encoding="utf-8"?>` at top of the file by using the `NewMapXmlSeq` cause I want to preserve the format and some comments in the file.

But I could only get the result `map[#procinst:map[#target:xml #inst:version="1.0" encoding="utf-8"]]`,
and the returned error is `no root key`

As you mentioned in the doc:
```
comments, directives, and procinsts that are NOT part of a document with a root key will be returned as
  map[string]interface{} and the error value 'NoRoot'.
```

How can I get the whole map of the XML file? 
I thought it's quite common that `<?xml version="1.0" encoding="utf-8"?>` not belong to any root

**Comment by clbanning** [comment]
I'll see what I can do -

**Comment by clbanning** [comment]
If you want the whole file in a single map[string]interface{} do something like:
`fh, err := os.Open(file)
 if err != nil {
      // handle error
}
defer fh.Close()
 m := make(map[string]interface{})
 for {
     v, err = mxi.NewMapXmlSeqReader(fh)
     if err != nil {
          if err == io.EOF {
               break;
           }
           // handle error
     }
     for key, val := range v {
          m[key] = val
      }
  }
  // do something with 'm'
`

**Comment by s850042002** [comment]
I got the same result using above code. I also simplified the XML file.

The loop break at the second round met the EOF so I could only get the `map[#procinst:map[#target:xml #inst:version="1.0" encoding="utf-8"]]`

```
<?xml version="1.0" encoding="utf-8"?>
<Configuration>
	<Name>QQ</Name>
</Configuration>
```

**Comment by clbanning** [comment]
Try the following with your data in "gitissue2.dat"

<pre>
package main

import (
	"bytes"
	"fmt"
	"github.com/clbanning/mxj"
	"io"
	"io/ioutil"
)

var data = []byte(`
<?xml version="1.0" encoding="utf-8"?>
<doc><elem>just something to demo</elem></doc>
`)

func main() {
	b, err := ioutil.ReadFile("gitissue2.dat")
	if err != nil {
		fmt.Println("err:", err)
		return
	}
	r := bytes.NewReader(b)
	m := make(map[string]interface{})
	for {
		v, err := mxj.NewMapXmlSeqReader(r)
		if err != nil {
			if err == io.EOF {
				break
			}
			if err != mxj.NoRoot {
				// handle error
			}
		}
		for key, val := range v {
			m[key] = val
		}
	}
	fmt.Printf("%v\n", m)
}
</pre

**Comment by clbanning** [comment]
<pre>
package main

import (
   "bytes"
   "fmt"
   "github.com/clbanning/mxj"
   "io"
   "io/ioutil"
)

func main() {
   b, err := ioutil.ReadFile("gitissue2.dat")
   if err != nil {
      fmt.Println("err:", err)
      return
   }
   r := bytes.NewReader(b)
   m := make(map[string]interface{})
   for {
      v, err := mxj.NewMapXmlSeqReader(r)
      if err != nil {
         if err == io.EOF {
            break
         }
         if err != mxj.NoRoot {
            // handle error
         }
      }
      for key, val := range v {
         m[key] = val
      }
   }
   fmt.Printf("%v\n", m)
}
</pre>

**Comment by s850042002** [comment]
It works, thanks a lot.

**Comment by clbanning** [comment]
There was an issue - it has to do with how xml.NewDecoder treats *os.File as a reader.  I added a work around to NewMapXmlReader() and NewMapXmlSeqReader() so that the original code I proposed will now work.  Thanks for the use-case.

**Comment by s850042002** [comment]
Updated and it works well. :+1:

**Comment by clbanning** [comment]
To re-encode the MapSeq value(s) to XML try:
```
package main

import (
	"bytes"
	"fmt"
	"io"
	"io/ioutil"

	"github.com/clbanning/mxj"
)

func main() {
	b, err := ioutil.ReadFile("gitissue2.dat")
	if err != nil {
		fmt.Println("err:", err)
		return
	}
	r := bytes.NewReader(b)
	m := make(map[string]interface{})
	for {
		v, err := mxj.NewMapXmlSeqReader(r)
		if err != nil {
			if err == io.EOF {
				break
			}
			if err != mxj.NoRoot {
				// handle error
			}
		}
		for key, val := range v {
			m[key] = val
		}
	}
	fmt.Printf("%v\n", m)

	// re-endcode as XML
	newXML := []byte{}
	for key, val := range m {
		b, err := mxj.MapSeq(val.(map[string]interface{})).Xml(key)
		if err != nil {
			fmt.Println("err:", err)
			return
		}
		newXML = append(newXML, b...)
	}
	fmt.Println(string(newXML))
}
```

Also, what is "xmlfile" you're referring to.  Certainly not "gitissue2.dat."
