### ISSUE TITLE
Reading directly from reader will fail parse, but writing and reading again succeed 

### ISSUE THREAD

**Issue by Spivaka** [clbanning/mxj#18]
When getting the following perfectly valid XML (a response from PANW Wildfire component):
`<?xml version="1.0" encoding="UTF-8"?>
<wildfire>
    <version>2.0</version>
    <file_info>
        <malware>yes</malware>
        <sha1>b918d3b98f590d99ac3694b373958017256a22b4</sha1>
        <filetype>PE</filetype>
        <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256>
        <md5>7f638f13d0797ef9b1a393808dc93b94</md5>
        <size>55296</size>
    </file_info>
<task_info> 
<report>
  <version>3.0</version>
  <platform>2</platform>
  <software>Windows XP, Adobe Reader 9.4.0, Flash 10, Office 2007</software>
  <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256>
  <md5>7f638f13d0797ef9b1a393808dc93b94</md5>
  <size>55296</size>
  <malware>yes</malware>
  <summary>
    <entry details="WildFire test samples exercise the capabilities of the WildFire analysis engine for purposes of testing." id="105" score="1.0">This is a WildFire test sample</entry>
    <entry details="The Windows system folder contains configuration files and executables that control the underlying functions of the system. Malware often modifies the contents of this folder to manipulate the system, establish persistence, and avoid detection." id="2" score="0.4">Created or modified a file in the Windows system folder</entry>
    <entry details="Legitimate software creates or modifies files to preserve data across system restarts. Malware may create or modify files to deliver malicious payloads or maintain persistence on a system." id="3" score="0.1">Created or modified a file</entry>
    <entry details="The Windows Registry houses system configuration settings and options, including information about installed applications, services, and drivers. Malware often modifies registry data to establish persistence on the system and avoid detection." id="13" score="0.1">Modified the Windows Registry</entry>
  </summary>
  <evidence>
    <file/>
    <registry/>
    <process/>
    <mutex/>
  </evidence>
  <timeline>
    <entry seq="1">Created Process c:\documents and settings\administrator\sample.exe</entry>
    <entry seq="2">Set key \REGISTRY\MACHINE\SOFTWARE\PaloAlto\PanCar to value 1</entry>
  </timeline>
  <network>
    <UDP country="CO" ip="191.233.81.105" port="123"/>
    <dns query="akadns.net" response="a1-128.akadns.net" type="NS"/>
    <dns query="akadns.net" response="a3-129.akadns.net" type="NS"/>
    <dns query="akadns.net" response="a9-128.akadns.net" type="NS"/>
    <dns query="akadns.net" response="a28-129.akadns.org" type="NS"/>
    <dns query="akadns.net" response="a13-130.akadns.org" type="NS"/>
    <dns query="akadns.net" response="a11-129.akadns.net" type="NS"/>
    <dns query="akadns.net" response="a5-130.akadns.org" type="NS"/>
    <dns query="akadns.net" response="a4-131.akadns.org" type="NS"/>
    <dns query="time.windows.com" response="191.233.81.105" type="A"/>
    <dns query="akadns.net" response="a10-128.akadns.org" type="NS"/>
    <dns query="akadns.net" response="a7-131.akadns.net" type="NS"/>
  </network>
  <process_tree>
    <process name="sample.exe" pid="1372" text="c:\documents and settings\administrator\sample.exe"/>
  </process_tree>
  <process_list>
    <process command="c:\documents and settings\administrator\sample.exe" name="sample.exe" pid="1372">
      <process_activity/>
      <registry>
        <Create key="HKEY_LOCAL_MACHINE" subkey="Software\PaloAlto"/>
        <Set data="1" key="\REGISTRY\MACHINE\SOFTWARE\PaloAlto" subkey="PanCar"/>
      </registry>
      <file/>
      <service/>
      <mutex/>
      <java_api/>
    </process>
  </process_list>
</report>
<report>
  <version>3.0</version>
  <platform>5</platform>
  <software>Windows 7 x64 SP1, Adobe Reader 11, Flash 11, Office 2010</software>
  <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256>
  <md5>7f638f13d0797ef9b1a393808dc93b94</md5>
  <size>55296</size>
  <malware>yes</malware>
  <summary>
    <entry details="WildFire test samples exercise the capabilities of the WildFire analysis engine for purposes of testing." id="105" score="1.0">This is a WildFire test sample</entry>
    <entry details="Legitimate software creates or modifies files to preserve data across system restarts. Malware may create or modify files to deliver malicious payloads or maintain persistence on a system." id="3" score="0.1">Created or modified a file</entry>
    <entry details="The Windows Registry houses system configuration settings and options, including information about installed applications, services, and drivers. Malware often modifies registry data to establish persistence on the system and avoid detection." id="13" score="0.1">Modified the Windows Registry</entry>
  </summary>
  <evidence>
    <file/>
    <registry/>
    <process/>
    <mutex/>
  </evidence>
  <timeline>
    <entry seq="1">Created Process C:\Users\Administrator\sample.exe</entry>
    <entry seq="2">Set key \REGISTRY\MACHINE\SOFTWARE\Wow6432Node\PaloAlto\PanCar to value 1</entry>
  </timeline>
  <network>
    <UDP country="CO" ip="191.233.81.105" port="123"/>
    <dns query="akadns.net" response="a7-131.akadns.net" type="NS"/>
    <dns query="akadns.net" response="a13-130.akadns.org" type="NS"/>
    <dns query="akadns.net" response="a3-129.akadns.net" type="NS"/>
    <dns query="akadns.net" response="a9-128.akadns.net" type="NS"/>
    <dns query="akadns.net" response="a28-129.akadns.org" type="NS"/>
    <dns query="akadns.net" response="a11-129.akadns.net" type="NS"/>
    <dns query="akadns.net" response="a5-130.akadns.org" type="NS"/>
    <dns query="akadns.net" response="a4-131.akadns.org" type="NS"/>
    <dns query="time.windows.com" response="191.233.81.105" type="A"/>
    <dns query="akadns.net" response="a10-128.akadns.org" type="NS"/>
    <dns query="akadns.net" response="a1-128.akadns.net" type="NS"/>
  </network>
  <process_tree>
    <process name="sample.exe" pid="1684" text="C:\Users\Administrator\sample.exe"/>
  </process_tree>
  <process_list>
    <process command="C:\Users\Administrator\sample.exe" name="sample.exe" pid="1684">
      <process_activity/>
      <registry>
        <Create key="HKEY_LOCAL_MACHINE" subkey="Software\PaloAlto"/>
        <Set data="1" key="\REGISTRY\MACHINE\SOFTWARE\Wow6432Node\PaloAlto" subkey="PanCar"/>
      </registry>
      <file/>
      <service/>
      <mutex/>
      <java_api/>
    </process>
  </process_list>
</report>
<report>
  <version>3.0</version>
  <platform>204</platform>
  <software>PE Static Analyzer</software>
  <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256>
  <md5>7f638f13d0797ef9b1a393808dc93b94</md5>
  <malware>no</malware>
  <summary>
    <entry details="The PE file checksum is required for drivers, boot-time DLLs, and other DLLs loaded into secure system processes. Malware often ignores this value or sets it to zero." id="3015" score="0.0">Contains an invalid checksum</entry>
    <entry details="Sections with a large discrepancy between raw and virtual sizes may indicate a packed or obfuscated PE file." id="3013" score="0.0">Contains sections with size discrepancies</entry>
  </summary>
</report>
</task_info> 
</wildfire>`
And using the following function:
`func ParseXMLResponseToJSON(reader io.Reader, resEntry *domain.Entry) error {
	b, err := ioutil.ReadAll(reader)
	if err != nil {
		return err
	}
	fmt.Println(string(b))
	reader = bytes.NewReader(b)
	m, err := mxj.NewMapXmlReader(reader)
	if err != nil {
		return err
	}
	content, err := json.Marshal(m)
	if err != nil {
		return err
	}
	return string(content)
}`
I get the response in json. However, when I read direcly from the reader:
`func ParseXMLResponseToJSON(reader io.Reader, resEntry *domain.Entry) error {
	/*b, err := ioutil.ReadAll(reader)
	if err != nil {
		return err
	}
	fmt.Println(string(b))*/
	reader = bytes.NewReader(b)
	m, err := mxj.NewMapXmlReader(reader)
	if err != nil {
		return err
	}
	content, err := json.Marshal(m)
	if err != nil {
		return err
	}
	return string(content)`
I get the following error:
`xml.Decoder.Token() - XML syntax error on line 135: unexpected EOF`

**Comment by clbanning** [comment]
Also comment out "reader = bytes.NewReader(b)" - just hand the "reader" argument to NewMapXmlReader() and see if that doesn't work.

**Comment by Spivaka** [comment]
our signature is a bit different, didn't want to make you dive into it so simplified it to return strings:
`func parseFromXml(reader io.Reader) (string, error) {
/*
	b, err := ioutil.ReadAll(reader)

	if err != nil {
		return "", err
	}
	fmt.Println(string(b))
	reader = bytes.NewReader(b)
*/
	m, err := mxj.NewMapXmlReader(reader)

	if err != nil {
		return "", err
	}
	content, err := json.Marshal(m)
	if err != nil {
		return "", err
	}
	return string(content), nil
}`
This code parse the attached XML only when the commented code is commented out. Otherwise it return the above error.

**Comment by clbanning** [comment]
I guess I don't understand what you're trying
      to do. 
      
      If you want to use ioutil.ReadAll(reader), the just call
      mxj.NewMapXml(b). 
    
    On 4/13/16 6:38 AM, Amichay Spivak
      wrote:
    
    
      our signature is a bit different, didn't want to make you dive
        into it so simplified it to return strings:
        `func parseFromXml(reader io.Reader) (string, error) {
        /*
        b, err := ioutil.ReadAll(reader)
      if err != nil {
    return "", err
}
fmt.Println(string(b))
reader = bytes.NewReader(b)

      */
        m, err := mxj.NewMapXmlReader(reader)
      if err != nil {
    return "", err
}
content, err := json.Marshal(m)
if err != nil {
    return "", err
}
return string(content), nil

      }`
        This code parse the attached XML only when the commented code is
        commented out. Otherwise it return the above error.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub

**Comment by Spivaka** [comment]
I am trying to read a response.Body reader with the XML provided above.
When I provide it directly to mxj.NewMapXmlReader(reader) it fails with the error:
`xml.Decoder.Token() - XML syntax error on line 135: unexpected EOF`
If I write it to a byte array and read it again, it functions fine.

**Comment by clbanning** [comment]
The example file I posted does that directly. 
      Did you run it?
    
    On 4/13/16 6:59 AM, Amichay Spivak
      wrote:
    
    
      I am trying to read a response.Body reader with the XML
        provided above.
        When I provide it directly to mxj.NewMapXmlReader(reader) it
        fails with the error:
        xml.Decoder.Token() - XML syntax error on line 135:
          unexpected EOF
        If I write it to a byte array and read it again, it functions
        fine.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub

**Comment by clbanning** [comment]
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/clbanning/mxj"
	"io"
)

var data = []byte(`<?xml version="1.0" encoding="UTF-8"?> <wildfire> <version>2.0</version> <file_info> <malware>yes</malware> <sha1>b918d3b98f590d99ac3694b373958017256a22b4</sha1> <filetype>PE</filetype> <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256> <md5>7f638f13d0797ef9b1a393808dc93b94</md5> <size>55296</size> </file_info> <task_info> <report> <version>3.0</version> <platform>2</platform> <software>Windows XP, Adobe Reader 9.4.0, Flash 10, Office 2007</software> <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256> <md5>7f638f13d0797ef9b1a393808dc93b94</md5> <size>55296</size> <malware>yes</malware> <summary> <entry details="WildFire test samples exercise the capabilities of the WildFire analysis engine for purposes of testing." id="105" score="1.0">This is a WildFire test sample</entry> <entry details="The Windows system folder contains configuration files and executables that control the underlying functions of the system. Malware often modifies the contents of this folder to manipulate the system, establish persistence, and avoid detection." id="2" score="0.4">Created or modified a file in the Windows system folder</entry> <entry details="Legitimate software creates or modifies files to preserve data across system restarts. Malware may create or modify files to deliver malicious payloads or maintain persistence on a system." id="3" score="0.1">Created or modified a file</entry> <entry details="The Windows Registry houses system configuration settings and options, including information about installed applications, services, and drivers. Malware often modifies registry data to establish persistence on the system and avoid detection." id="13" score="0.1">Modified the Windows Registry</entry> </summary> <evidence> <file/> <registry/> <process/> <mutex/> </evidence> <timeline> <entry seq="1">Created Process c:\documents and settings\administrator\sample.exe</entry> <entry seq="2">Set key \REGISTRY\MACHINE\SOFTWARE\PaloAlto\PanCar to value 1</entry> </timeline> <network> <UDP country="CO" ip="191.233.81.105" port="123"/> <dns query="akadns.net" response="a1-128.akadns.net" type="NS"/> <dns query="akadns.net" response="a3-129.akadns.net" type="NS"/> <dns query="akadns.net" response="a9-128.akadns.net" type="NS"/> <dns query="akadns.net" response="a28-129.akadns.org" type="NS"/> <dns query="akadns.net" response="a13-130.akadns.org" type="NS"/> <dns query="akadns.net" response="a11-129.akadns.net" type="NS"/> <dns query="akadns.net" response="a5-130.akadns.org" type="NS"/> <dns query="akadns.net" response="a4-131.akadns.org" type="NS"/> <dns query="time.windows.com" response="191.233.81.105" type="A"/> <dns query="akadns.net" response="a10-128.akadns.org" type="NS"/> <dns query="akadns.net" response="a7-131.akadns.net" type="NS"/> </network> <process_tree> <process name="sample.exe" pid="1372" text="c:\documents and settings\administrator\sample.exe"/> </process_tree> <process_list> <process command="c:\documents and settings\administrator\sample.exe" name="sample.exe" pid="1372"> <process_activity/> <registry> <Create key="HKEY_LOCAL_MACHINE" subkey="Software\PaloAlto"/> <Set data="1" key="\REGISTRY\MACHINE\SOFTWARE\PaloAlto" subkey="PanCar"/> </registry> <file/> <service/> <mutex/> <java_api/> </process> </process_list> </report> <report> <version>3.0</version> <platform>5</platform> <software>Windows 7 x64 SP1, Adobe Reader 11, Flash 11, Office 2010</software> <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256> <md5>7f638f13d0797ef9b1a393808dc93b94</md5> <size>55296</size> <malware>yes</malware> <summary> <entry details="WildFire test samples exercise the capabilities of the WildFire analysis engine for purposes of testing." id="105" score="1.0">This is a WildFire test sample</entry> <entry details="Legitimate software creates or modifies files to preserve data across system restarts. Malware may create or modify files to deliver malicious payloads or maintain persistence on a system." id="3" score="0.1">Created or modified a file</entry> <entry details="The Windows Registry houses system configuration settings and options, including information about installed applications, services, and drivers. Malware often modifies registry data to establish persistence on the system and avoid detection." id="13" score="0.1">Modified the Windows Registry</entry> </summary> <evidence> <file/> <registry/> <process/> <mutex/> </evidence> <timeline> <entry seq="1">Created Process C:\Users\Administrator\sample.exe</entry> <entry seq="2">Set key \REGISTRY\MACHINE\SOFTWARE\Wow6432Node\PaloAlto\PanCar to value 1</entry> </timeline> <network> <UDP country="CO" ip="191.233.81.105" port="123"/> <dns query="akadns.net" response="a7-131.akadns.net" type="NS"/> <dns query="akadns.net" response="a13-130.akadns.org" type="NS"/> <dns query="akadns.net" response="a3-129.akadns.net" type="NS"/> <dns query="akadns.net" response="a9-128.akadns.net" type="NS"/> <dns query="akadns.net" response="a28-129.akadns.org" type="NS"/> <dns query="akadns.net" response="a11-129.akadns.net" type="NS"/> <dns query="akadns.net" response="a5-130.akadns.org" type="NS"/> <dns query="akadns.net" response="a4-131.akadns.org" type="NS"/> <dns query="time.windows.com" response="191.233.81.105" type="A"/> <dns query="akadns.net" response="a10-128.akadns.org" type="NS"/> <dns query="akadns.net" response="a1-128.akadns.net" type="NS"/> </network> <process_tree> <process name="sample.exe" pid="1684" text="C:\Users\Administrator\sample.exe"/> </process_tree> <process_list> <process command="C:\Users\Administrator\sample.exe" name="sample.exe" pid="1684"> <process_activity/> <registry> <Create key="HKEY_LOCAL_MACHINE" subkey="Software\PaloAlto"/> <Set data="1" key="\REGISTRY\MACHINE\SOFTWARE\Wow6432Node\PaloAlto" subkey="PanCar"/> </registry> <file/> <service/> <mutex/> <java_api/> </process> </process_list> </report> <report> <version>3.0</version> <platform>204</platform> <software>PE Static Analyzer</software> <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256> <md5>7f638f13d0797ef9b1a393808dc93b94</md5> <malware>no</malware> <summary> <entry details="The PE file checksum is required for drivers, boot-time DLLs, and other DLLs loaded into secure system processes. Malware often ignores this value or sets it to zero." id="3015" score="0.0">Contains an invalid checksum</entry> <entry details="Sections with a large discrepancy between raw and virtual sizes may indicate a packed or obfuscated PE file." id="3013" score="0.0">Contains sections with size discrepancies</entry> </summary> </report> </task_info> </wildfire>`)

func main() {
	_, err := mxj.NewMapXml(data)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("ok")

	// reader := bytes.NewReader(data)
	reader := bytes.NewReader([]byte(""))
	if _, err := ParseXMLResponseToJSON(reader); err != nil {
		fmt.Println(err)
	}
}

func ParseXMLResponseToJSON(reader io.Reader) (string, error) {
	/*b, err := ioutil.ReadAll(reader)
	  if err != nil { return err }
	  fmt.Println(string(b))
	*/
	// reader = bytes.NewReader(b)
	m, err := mxj.NewMapXmlReader(reader)
	if err != nil {
		return "", err
	}
	content, err := json.Marshal(m)
	if err != nil {
		return "", err
	}
	return string(content), nil
}

**Comment by clbanning** [comment]
I suspect that using ioutil.ReadAll() is the
      problem - it stops at io.EOF so when you pass it to
      mxj.NewMapXmlReader() the xml.Decoder is trying to read past the
      end of the io.Reader buffer.  That's why it works when you
      reinitialize the 'reader' from the []byte slice you read with
      ioutil.ReadAll().
    
    On 4/13/16 6:59 AM, Amichay Spivak
      wrote:
    
    
      I am trying to read a response.Body reader with the XML
        provided above.
        When I provide it directly to mxj.NewMapXmlReader(reader) it
        fails with the error:
        xml.Decoder.Token() - XML syntax error on line 135:
          unexpected EOF
        If I write it to a byte array and read it again, it functions
        fine.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub

**Comment by Spivaka** [comment]
No, it isn't. When I get the reader in the first time (actually from the go http client) I get the error. 
When I write the data in that reader to a byte, and than read it again - everything works fine.
By the way - this worked fine till the end of last month, when probably something was pushed to make it stop working.
As a matter of fact, I've forked the code from around the 20 of march as a workaround.

**Comment by clbanning** [comment]
I suspect I know what might be happening, but I
      can't reproduce your error.  Can you send me a snippet that I can
      just run and get the error you're seeing.  Then I can trace what's
      going on.
    
    On 4/13/16 10:40 AM, Amichay Spivak
      wrote:
    
    
      No, it isn't. When I get the reader in the first time (actually
        from the go http client) I get the error. 
        When I write the data in that reader to a byte, and than read it
        again - everything works fine.
        By the way - this worked fine till the end of last month, when
        probably something was pushed to make it stop working.
        As a matter of fact, I've forked the code from around the 20 of
        march as a workaround.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub

**Comment by Spivaka** [comment]
Hi, 
This code should reproduce the error (without revealing my wildfire private key):
`func TestExample(t *testing.T) {
	httpmock.Activate()
	defer httpmock.DeactivateAndReset()
	expectedResponse := `<?xml version="1.0" encoding="UTF-8"?> <wildfire> <version>2.0</version> <file_info> <malware>yes</malware> <sha1>b918d3b98f590d99ac3694b373958017256a22b4</sha1> <filetype>PE</filetype> <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256> <md5>7f638f13d0797ef9b1a393808dc93b94</md5> <size>55296</size> </file_info> <task_info> <report> <version>3.0</version> <platform>2</platform> <software>Windows XP, Adobe Reader 9.4.0, Flash 10, Office 2007</software> <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256> <md5>7f638f13d0797ef9b1a393808dc93b94</md5> <size>55296</size> <malware>yes</malware> <summary> <entry details="WildFire test samples exercise the capabilities of the WildFire analysis engine for purposes of testing." id="105" score="1.0">This is a WildFire test sample</entry> <entry details="The Windows system folder contains configuration files and executables that control the underlying functions of the system. Malware often modifies the contents of this folder to manipulate the system, establish persistence, and avoid detection." id="2" score="0.4">Created or modified a file in the Windows system folder</entry> <entry details="Legitimate software creates or modifies files to preserve data across system restarts. Malware may create or modify files to deliver malicious payloads or maintain persistence on a system." id="3" score="0.1">Created or modified a file</entry> <entry details="The Windows Registry houses system configuration settings and options, including information about installed applications, services, and drivers. Malware often modifies registry data to establish persistence on the system and avoid detection." id="13" score="0.1">Modified the Windows Registry</entry> </summary> <evidence> <file/> <registry/> <process/> <mutex/> </evidence> <timeline> <entry seq="1">Created Process c:\documents and settings\administrator\sample.exe</entry> <entry seq="2">Set key \REGISTRY\MACHINE\SOFTWARE\PaloAlto\PanCar to value 1</entry> </timeline> <network> <UDP country="CO" ip="191.233.81.105" port="123"/> <dns query="akadns.net" response="a1-128.akadns.net" type="NS"/> <dns query="akadns.net" response="a3-129.akadns.net" type="NS"/> <dns query="akadns.net" response="a9-128.akadns.net" type="NS"/> <dns query="akadns.net" response="a28-129.akadns.org" type="NS"/> <dns query="akadns.net" response="a13-130.akadns.org" type="NS"/> <dns query="akadns.net" response="a11-129.akadns.net" type="NS"/> <dns query="akadns.net" response="a5-130.akadns.org" type="NS"/> <dns query="akadns.net" response="a4-131.akadns.org" type="NS"/> <dns query="time.windows.com" response="191.233.81.105" type="A"/> <dns query="akadns.net" response="a10-128.akadns.org" type="NS"/> <dns query="akadns.net" response="a7-131.akadns.net" type="NS"/> </network> <process_tree> <process name="sample.exe" pid="1372" text="c:\documents and settings\administrator\sample.exe"/> </process_tree> <process_list> <process command="c:\documents and settings\administrator\sample.exe" name="sample.exe" pid="1372"> <process_activity/> <registry> <Create key="HKEY_LOCAL_MACHINE" subkey="Software\PaloAlto"/> <Set data="1" key="\REGISTRY\MACHINE\SOFTWARE\PaloAlto" subkey="PanCar"/> </registry> <file/> <service/> <mutex/> <java_api/> </process> </process_list> </report> <report> <version>3.0</version> <platform>5</platform> <software>Windows 7 x64 SP1, Adobe Reader 11, Flash 11, Office 2010</software> <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256> <md5>7f638f13d0797ef9b1a393808dc93b94</md5> <size>55296</size> <malware>yes</malware> <summary> <entry details="WildFire test samples exercise the capabilities of the WildFire analysis engine for purposes of testing." id="105" score="1.0">This is a WildFire test sample</entry> <entry details="Legitimate software creates or modifies files to preserve data across system restarts. Malware may create or modify files to deliver malicious payloads or maintain persistence on a system." id="3" score="0.1">Created or modified a file</entry> <entry details="The Windows Registry houses system configuration settings and options, including information about installed applications, services, and drivers. Malware often modifies registry data to establish persistence on the system and avoid detection." id="13" score="0.1">Modified the Windows Registry</entry> </summary> <evidence> <file/> <registry/> <process/> <mutex/> </evidence> <timeline> <entry seq="1">Created Process C:\Users\Administrator\sample.exe</entry> <entry seq="2">Set key \REGISTRY\MACHINE\SOFTWARE\Wow6432Node\PaloAlto\PanCar to value 1</entry> </timeline> <network> <UDP country="CO" ip="191.233.81.105" port="123"/> <dns query="akadns.net" response="a7-131.akadns.net" type="NS"/> <dns query="akadns.net" response="a13-130.akadns.org" type="NS"/> <dns query="akadns.net" response="a3-129.akadns.net" type="NS"/> <dns query="akadns.net" response="a9-128.akadns.net" type="NS"/> <dns query="akadns.net" response="a28-129.akadns.org" type="NS"/> <dns query="akadns.net" response="a11-129.akadns.net" type="NS"/> <dns query="akadns.net" response="a5-130.akadns.org" type="NS"/> <dns query="akadns.net" response="a4-131.akadns.org" type="NS"/> <dns query="time.windows.com" response="191.233.81.105" type="A"/> <dns query="akadns.net" response="a10-128.akadns.org" type="NS"/> <dns query="akadns.net" response="a1-128.akadns.net" type="NS"/> </network> <process_tree> <process name="sample.exe" pid="1684" text="C:\Users\Administrator\sample.exe"/> </process_tree> <process_list> <process command="C:\Users\Administrator\sample.exe" name="sample.exe" pid="1684"> <process_activity/> <registry> <Create key="HKEY_LOCAL_MACHINE" subkey="Software\PaloAlto"/> <Set data="1" key="\REGISTRY\MACHINE\SOFTWARE\Wow6432Node\PaloAlto" subkey="PanCar"/> </registry> <file/> <service/> <mutex/> <java_api/> </process> </process_list> </report> <report> <version>3.0</version> <platform>204</platform> <software>PE Static Analyzer</software> <sha256>dd8e64991f68eeebb52c9947ea56f39a776185d1a076741533aa6843022c03b0</sha256> <md5>7f638f13d0797ef9b1a393808dc93b94</md5> <malware>no</malware> <summary> <entry details="The PE file checksum is required for drivers, boot-time DLLs, and other DLLs loaded into secure system processes. Malware often ignores this value or sets it to zero." id="3015" score="0.0">Contains an invalid checksum</entry> <entry details="Sections with a large discrepancy between raw and virtual sizes may indicate a packed or obfuscated PE file." id="3013" score="0.0">Contains sections with size discrepancies</entry> </summary> </report> </task_info> </wildfire>`
	address := "http://83.83.83.83/test"
	httpmock.RegisterResponder("POST",
		address,
		httpmock.NewStringResponder(200, expectedResponse))
	request, err := http.NewRequest("POST", address, nil)
	if err != nil {
		t.Fatalf(err.Error())
	}
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		t.Fatalf(err.Error())
	}
	/*
		b, err := ioutil.ReadAll(reader)

		if err != nil {
			return "", err
		}
		fmt.Println(string(b))
		reader = bytes.NewReader(b)
	*/
	m, err := mxj.NewMapXmlReader(response.Body)

	if err != nil {
		t.Fatalf(err.Error())
	}
	content, err := json.Marshal(m)
	if err != nil {
		t.Fatalf(err.Error())
	}
	fmt.Println(string(content))
}`

However - it doesn't. when I run the same code without the mock and using my key, I get the error above.

I believe that the response from PANW wildfire ends in a manner that is not compatible to your code... If this is very specific, I think reading and writing to a byte array is a WA that I can live with

**Comment by clbanning** [comment]
The error "XML syntax error on line 135: unexpected EOF" is coming from the stdlib encoding/xml Decoder method "Token()". The only thing the mxj code does is wrap any io.Reader argument in a io.ByteReader() for the xml.Decoder to use if needed. So there must be some difference between your httpmock Response.Body and the stdlib http Response.Body which is an io.ReadCloser even though they both satisfy the io.Reader interface.

I have a theory what might be happening, but I don't have time right now to build out a text case.  I've, however, changed the ByteReader error handling, see if that doesn't help.

**Comment by clbanning** [comment]
If you are using jarcoal/httpmock your response value is an io.ReadSeeker and it's Read method doesn't return io.EOF at the end, rather it resets the reader to the beginning of the buffer so you can call it again.

**Comment by clbanning** [comment]
I've made one additional change this morning to guard against conditions where net/http.Response.Body.Read returns a byte value and an informational error.  Hopefully, now you can use NewMapXmlReader() as intended.
