### ISSUE TITLE
Failed to parse xml to map when attributes contain special characters (&, >, <, ', ")

### ISSUE THREAD

**Issue by minhduccm** [clbanning/mxj#19]
Hi @clbanning , I have xml document below and got error `xml.Decoder.Token() - XML syntax error on line 2: invalid character entity & (no semicolon)` when parsing xml to map:

`<document>
<name>Bill & Hallett</name>
<salute>Duc &amp; 123xx</salute>
<goes_by/>
<lang>E</lang>
</document>`

Just read your code, and found problem at `xmlToMapParser` function. You're using `xml.Decoder` with `Strict=true` by default that dose not allow special characters (https://golang.org/pkg/encoding/xml/#Decoder) 

Could you fix it or expose some ways to enable/disable `Strict` mode from xm.Decoder object?

**Comment by clbanning** [comment]
Thanks.  I've written the test case.  Probably not adequate to just handle Strict mode; I believe that the solution should handle all Decoder options.  Will work on that.

**Comment by clbanning** [comment]
Done. See documentation on package variable CustomDecoder.
