### ISSUE TITLE
Replace Hypen with standard Javascript Character

### ISSUE THREAD

**Issue by u382514** [clbanning/mxj#20]
This is a great library! Thanks for making this. When converting XML to JSON should we be using a Hypen for attributes? Why not use an underscore? The reason being is that this library is highly useful for server side processing where it concerns Javascript...so turning that JSON into a POJO would be better aligned using an underscore...unfortunately the $ sign is way to overused.

**Comment by clbanning** [comment]
I'll look into that as an option later this
        weekend. Thanks.
    
    
    On 6/25/16 12:16 AM, Brandon Jonson
      wrote:
    
    
      This is a great library! Thanks for making this. When
        converting XML to JSON should we be using a Hypen for
        attributes? Why not use an underscore? The reason being is that
        this library is highly useful for server side processing where
        it concerns Javascript...so turning that JSON into a POJO would
        be better aligned using an underscore...unfortunately the $ sign
        is way to overused. 
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.

**Comment by clbanning** [comment]
See new SetAttrPrefix() function.

**Comment by u382514** [comment]
You rock!
