### ISSUE TITLE
j2x does not encode < > &

### ISSUE THREAD

**Issue by nielsbergsma** [clbanning/mxj#21]
Hi,

It seems like special xml characters don't get encoded:

Test case:
`json := "{ \"test\": \"a&b <c>\" }"`
`xml, _ := j2x.JsonToXml([]byte(json))`
`fmt.Printf("xml %v\n", string(xml))`

Output:
`xml <test>a&b <c></test>`

How can we encode these values?

**Comment by clbanning** [comment]
Try:
<pre>
package main

import (
   "fmt"
   "github.com/clbanning/mxj"
   "github.com/clbanning/mxj/j2x"
)

func main() {
   j := []byte(`{"test": "a&b <c>"}`)

   mxj.XMLEscapeChars(true)
   x, err := j2x.JsonToXml(j)
   if err != nil {
      fmt.Println("err:", err)
   }
   fmt.Printf("xml %v\n", string(x))
}
</pre>

Output:
   ```xml <test>a&amp;b &lt;c&gt;</test>```

**Comment by nielsbergsma** [comment]
Awesome! thanks
