### ISSUE TITLE
XMLEscapeChars don't seem to be working

### ISSUE THREAD

**Issue by RoanBrand** [clbanning/mxj#22]
I have this:

```
mxj.XMLEscapeChars(true)
final, err := newImport.XmlSeq()
_, err = io.WriteString(fo, string(final))
```

The output file shows: `<shortDescription>>0-2y</shortDescription>`

The original source is: `<shortDescription>&gt;0-2y</shortDescription>`

and that is the way I want it output. Am I missing something?

**Comment by RoanBrand** [comment]
Looks like I read documentation line 17 in `escapechars.go` too fast.
What can I do to output the XML while preserving original order and escape the invalid chars?

I use this to read the original xml:
```
raw, err := ioutil.ReadFile(file)
		if err != nil {
			return err
		}

		r := bytes.NewReader(raw)
		m := make(mxj.Map)
		for {
			v, err := mxj.NewMapXmlSeqReader(r)
			if err != nil {
				if err == io.EOF {
					break
				}
				if err != mxj.NoRoot {
					return err
				}
			}
			for key, val := range v {
				m[key] = val
			}
		}
```
After that, `m` already contains the invalid `<` & `>` chars

**Comment by clbanning** [comment]
Looks like I need to patch mv.XmlSeq() also.  I'll look into it later in the day.  Can you supply test data set?  Or I'll use:

<doc><shortDescription>&gt;0-2y</shortDescription></doc>

for source and output.

**Comment by clbanning** [comment]
There are two new test cases in "escapechars_test.go."  If they don't suite your use case, send me another.
