### ISSUE TITLE
using x2j to read xml from stdin and write json to stdout?

### ISSUE THREAD

**Issue by mewalig** [clbanning/mxj#24]
could anyone provide a compilable example using x2j for this simple task?

**Comment by clbanning** [comment]
<pre>
package main

import (
	"fmt"
	"os"
	"github.com/clbanning/mxj/x2j"
)

func main() {
	for {
		_, _, err := x2j.XmlReaderToJsonWriter(os.Stdin, os.Stdout)
		if err != nil {
			fmt.Println(err)
			break
		}
	}
}
</pre>

**Comment by mewalig** [comment]
thanks!

**Comment by mewalig** [comment]
is there any easy way, without changing the x2j library code, to stop it from printing "EOF" at the end?
