### ISSUE TITLE
x2j.XmlReaderToJsonWriter: outputting without "EOF"

### ISSUE THREAD

**Issue by mewalig** [clbanning/mxj#25]
Thanks for the example in https://github.com/clbanning/mxj/issues/24. The only issue is that the outputted JSON has an extra "EOF" at the end. How can this be removed from the output?

**Comment by clbanning** [comment]
I'll need an example you're running that
      reproduces the EOF - when I run the app interactively on OS X I
      don't get any "extra" characters.
    
    On 9/27/16 3:01 PM, mewalig wrote:
    
    
      Thanks for the example in #24.
        The only issue is that the outputted JSON has an extra "EOF" at
        the end. How can this be removed from the output?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/clbanning/mxj","title":"clbanning/mxj","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/clbanning/mxj"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"x2j.XmlReaderToJsonWriter: outputting without \"EOF\" (#25)"}],"action":{"name":"View Issue","url":"https://github.com/clbanning/mxj/issues/25"}}}

**Comment by clbanning** [comment]
<pre>
package main

import (
	"fmt"
	"io"
	"os"
	"github.com/clbanning/mxj/x2j"
)

func main() {
	for {
		_, _, err := x2j.XmlReaderToJsonWriter(os.Stdin, os.Stdout)
		if err == io.EOF {
			break
		}
		if err != nil {
			fmt.Println(err)
			break
		}
	}
}
</pre>

**Comment by mewalig** [comment]
that did it, thank you!
