### ISSUE TITLE
example of append

### ISSUE THREAD

**Issue by munkyboy** [clbanning/mxj#34]
I can't figure out how to append to a list. 
I want to change
```
<a>
  <b>1</b>
</a>
```
to
```
<a>
  <b>1</b>
  <b>2</b>
</a>
```

**Comment by clbanning** [comment]
Added a new example - examples/append.go.

Note, this package is a little weak for manipulating elements, since it was primarily written to process anonymous XML objects and extract values for map members.

**Comment by munkyboy** [comment]
cool. thanks for the quick reply!

**Comment by clbanning** [comment]
Just updated the example with additional doc.
    
    On 1/25/17 8:36 AM, Mike Luu wrote:
    
    
      cool. thanks for the quick reply!
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/clbanning/mxj","title":"clbanning/mxj","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/clbanning/mxj"}},"updates":{"snippets":[{"icon":"PERSON","message":"@munkyboy in #34: cool. thanks for the quick reply!"}],"action":{"name":"View Issue","url":"https://github.com/clbanning/mxj/issues/34#issuecomment-275140801"}}}

**Comment by munkyboy** [comment]
um, there might be some stuff in that last reply you want to remove

**Comment by clbanning** [comment]
Note: m.Xml/m.XmlIndent are not guaranteed to preserve the original element sequence of the DOC.  Doing the same append with NewMapXmlSeq is more complicated since you have to manage the #text and #seq keys.
