### ISSUE TITLE
Parse XML without closing tag

### ISSUE THREAD

**Issue by gudvinr** [clbanning/mxj#36]
Hello.

I'm trying to use library to parse XMPP stream.

This is can be done quite simple with `HandleXmlReader` and `NewXmlMapReader` but since everything is going after `<stream:stream>` until it'll be closed parser just got stuck.

If it's not possible to handle continuous streams I just want to skip starting tag and continue from next one. So at least passing `startElement` to begin parse with next token will be a fine solution.

**Comment by clbanning** [comment]
Please provide a data set so I can recreate the use case.

**Comment by clbanning** [comment]
I looked at the XMPP spec and added HandleXMPPStreamTag() function to address this.  I didn't just want to skip over the "stream" tag, since you might want to handle some the attributes at the head of a stream.

**Comment by gudvinr** [comment]
@clbanning glad to see this fixed so fast. Thanks, works like a charm.
