### ISSUE TITLE
Migration from x2j - ISSUE: DocToMap doesn't exist?

### ISSUE THREAD

**Issue by pathaugen** [clbanning/mxj#41]
Inherited a project and saw that x2j (https://github.com/clbanning/x2j) migrated to this mxj -

However "DocToMap(data)" isn't here in mxj. Is there a function that replaces that?

**Comment by clbanning** [comment]
x2j isn't going away - it just doesn't get anything new.  I did refactor it some time ago to use the more performant XML decoder from mxj, however, because x2j still gets cloned a lot. 

x2j.DocToMap is equivalent to:

    m, err := NewMapXml(data)
    if err != nil {
        // handle err
    }
    // you should be able to work with 'm' - but depending on what you're doing ...
    yourMap := m.Old() // same as yourMap := map[string]interface{}(m)
