### ISSUE TITLE
NewMapXml() simplifies single item arrays into items

### ISSUE THREAD

**Issue by shoobyban** [clbanning/mxj#45]
Hi,

Many thanks for writing and especially for maintaining the package.

When running NewMapXml() with an XML containing 2 or more items it results an `[]interface{}` of the items, otherwise only the item (mostly map[string]interface{}), see below:

```go
package main

import (
	"fmt"
	"io"
	"reflect"

	"github.com/clbanning/mxj"
)

func main() {
	type Map map[string]interface{}
	x := []byte(`<doc> 
		    <book>
			<author>A</author>
		    </book>
		    <book>
			<author>B</author>
		    </book>
                </doc>`)
	y := []byte(`<doc> 
		    <book>
			<author>A</author>
		    </book>
                </doc>`)

	m, err := mxj.NewMapXml(x)
	if err != nil && err != io.EOF {
		panic(err)
	}
	n, err := mxj.NewMapXml(y)
	if err != nil && err != io.EOF {
		panic(err)
	}
	m1 := reflect.ValueOf(m["doc"])
	n1 := reflect.ValueOf(n["doc"])
	if m1.MapIndex(m1.MapKeys()[0]) != n1.MapIndex(n1.MapKeys()[0]) {
		fmt.Printf("%#v != %#v", m1, n1)
	}
}
```

Tested it with go 1.10.1 and 1.7.0

**Comment by shoobyban** [comment]
I have found the part doing this, it's intentional, but I would argue that it's against computability.
```diff
diff --git a/xml.go b/xml.go
index 09c987f..6700fd9 100644
--- a/xml.go
+++ b/xml.go
@@ -398,7 +398,9 @@ func xmlToMapParser(skey string, a []xml.Attr, p *xml.Decoder, r bool) (map[stri
                                a = append(a, val)
                                na[key] = a
                        } else {
-                               na[key] = val // save it as a singleton
+                               var a []interface{}
+                               a = append(a, val)
+                               na[key] = a
                        }
                case xml.EndElement:
                        // len(n) > 0 if this is a simple element w/o xml.Attrs - see xml.CharData case.
```

**Comment by clbanning** [comment]
I guess what you're proposing (in a subsequent e-mail that isn't shown here) is that
```
   <doc><book><author>A</author></book></doc>
```
should decode to
```
  []interface{}{map[string]interface{}{"book":[]interface{}{map[string]interface{}{"author":"A"}}}}
```
which is equivalent to the JSON object:
```
   [{"book":[{"author":"A"}]}]
```
as opposed to the object:
```
   {"book":{"author":"A"}}
```
Unfortunately, the raw XML syntax does not provide the appropriate type information for decoding.  (Perhaps that is why encoding/xml in the stdlib does not support Unmarshaling to map[string]interface{} while encoding/json does.)

That would be major breaking change for this package affecting many methods, such as, <code>mv.UpdateValuesForPath(), mv.ValueForPath(),  mv.ValuesForPath"</code>, etc. - not to mention argument syntax changes.  

If you need this, I'd propose you fork the repo and add the patch you proposed.  (You'll need to handle or discard NewMapXmlSeq(), also.)

It is my perception that most use cases don't have to deal with such ambiguity, but if they do it is rather trivial to interrogate the interface{} value using a select statement to see if it's of []interface{} type and deal with it separately - just as <code>mv.Xml()</code> does.
