### ISSUE TITLE
FAIL: ExampleMap_Struct (0.00s)

### ISSUE THREAD

**Issue by nicolasStevenin** [clbanning/mxj#52]
Hi !

When I try to test your project, it fails in the current directory:

 **command: go test -buildmode pie -compiler gc -ldflags "-X github.com/clbanning/mxj/version=1.8.2 -extldflags '-Wl,-z,relro  '"**
   testing: github.com/clbanning/mxj

----------- TestXMPPStreamTagSeq ...

<stream:stream
    from='example.com'
    xmlns="jabber:client"
    xmlns:stream="http://etherx.jabber.org/streams"
    version="1.0">
map[stream:stream:map[#attr:map[from:map[#seq:0 #text:example.com] xmlns:map[#seq:1 #text:jabber:client] xmlns:stream:map[#text:http://etherx.jabber.org/streams #seq:2] version:map[#text:1.0 #seq:3]]]]

<stream:features>
  <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/>
  <sm xmlns="urn:xmpp:sm:3"/>
</stream:features>
map[stream:features:map[sm:map[#attr:map[xmlns:map[#seq:0 #text:urn:xmpp:sm:3]] #seq:1] bind:map[#attr:map[xmlns:map[#text:urn:ietf:params:xml:ns:xmpp-bind #seq:0]] #seq:0]]]

<stream:stream>
map[stream:stream:map[]]

--- FAIL: ExampleMap_Struct (0.00s)
got:
mapVal: mxj.Map{"private":"Somewhere over the rainbow", "int":4, "str":"now's the time", "float":3.14159, "bool":true}
strVal: mxj_test.str{IntVal:4, StrVal:"now's the time", FloatVal:3.14159, BoolVal:true, private:""}

want (unordered):
mapVal: mxj.Map{"int":4, "str":"now's the time", "float":3.14159, "bool":true, "private":"Somewhere over the rainbow"}
strVal: mxj_test.str{IntVal:4, StrVal:"now's the time", FloatVal:3.14159, BoolVal:true, private:""}

Thanks

**Comment by clbanning** [comment]
Thanks.  I've commented out all examples so "want" output values that can't be guaranteed do to randomness of map key:value pairs won't fail.  Also fixed another test issue.  See v1.8.3.
