### ISSUE TITLE
Proposal for adding capability to skip conversion for specific keys

### ISSUE THREAD

**Issue by amansardana** [clbanning/mxj#58]
Thanks for the great library, it is of great help.
I have a use case, In which I need to skip casting of value for few keys to numeric/bool. 
We can provide a function which takes in a regex/list of keys and sets them to skip casting for those keys.
Please let me know, what you think, I can write the function for this, and create a pull request.

**Comment by clbanning** [comment]
This is sure an edge case.  I assume that you're looking to just cast numeric values and not boolean ones. Or something like that.  I'd suggest you go ahead and modify your fork for now.  I'll think about it and look at your implementation and test cases.

**Comment by clbanning** [comment]
At tip there's a hook you can use for your regex/list to skip casting based on XML tag.  There are docs with the placeholder for your code that will need to be captured.
