### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by hrieke** [clbanning/mxj#61]
Hi,

In your documentation, you state that the code is licensed under the BSD 3 clause license.
When I reviewed the license file, it states first your name and the MIT License and then Go Language followed by the BSD 3 clause license.
 
Both are perfectly cool licenses, but could you clear up which one is the one that you actually selected?

Thanks

**Comment by clbanning** [comment]
The MIT license is mine.  (The license below the line is the Go license.  I'll remove it i it's confusing.)

**Comment by hrieke** [comment]
You might also want to look at the file doc.go which states the BSD license (unless of course it's from Go, in which case you might want to state that).

**Comment by clbanning** [comment]
Thanks - done.
