### ISSUE TITLE
NewMapXmlSeq: 'no root key'' error if there is a XML declaration

### ISSUE THREAD

**Issue by simonfrey** [clbanning/mxj#67]
I use the following XML for umarshaling it into a MapSeq. If there is a XML declaration (`<?xml version="1.0" encoding="UTF-8"?>`) the `NewMapXmlSeq` function returns the `no root key` error.

What made me wonder, is that if I use the exact same XML with NewMapXml all works without problems.

Any idea what could be wrong here?

Used XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
    <responseDate>2019-08-06T14:09:14Z</responseDate>
</OAI-PMH>
```

**Comment by clbanning** [comment]
The error is actually that NewMapXmlSeq is treating the declaration `<?xml ... ?>` as a process instruction and returning a map[#procinst:map[]] value along with the "no root key" message, which means with NewMapSeq to check the map value for a `#procinst`, `#comment` or `#directive` key if you want to parse it. 

 I'll work on fixing this later when I have some time.  Probably need more informative error messages and specific handling of "declaration," which is not a recognized type  in the stdlib `encoding/xml` package when parsing using the `Decoder.RawToken()` method call.

Thanks.

**Comment by clbanning** [comment]
NewMapXml using `Decoder.Token()` from the stdlib `encoding/xml` package.  That method skips doesn't return declarations, comments, directives or process instructions.

**Comment by clbanning** [comment]
I believe the behavior is correct.  A declaration is syntactically identical to a process instruction.  The documentation does say that if you receive a `NoRoot` error, you should interrogate the returned Map value to see if it has a `#comment`, `#directive` or `#procinst` key:value pair to handle it correctly. 

I'd like to wait for go1.13 when we'll be able to "wrap" errors and let `mxj.NoRoot` wrap `mxj.ErrComment`, etc.
