### ISSUE TITLE
[Bug]integer will be transformed to double

### ISSUE THREAD

**Issue by chenYunHsin-maker** [clbanning/mxj#69]
Input json: 
`"ipv4": {
						     	 "address-mode": "manual",
						     	 "address": {
							      "ip": "10.10.10.10",
							      "prefix-length": 30
							    }`

Output xml:
`<ipv4><address><ip>10.0.22.14</ip><prefix-length>30.000000</prefix-length></address><address-mode>manual</address-mode><enabled>true</enabled><mtu>1500.000000</mtu><vti_peer>10.10.10.10</vti_peer></ipv4>
`

In this case, prefix-length:30 became 30.000000
Do anyone have the same problem with me?

**Comment by clbanning** [comment]
You'll have to show me some code. the following looks ok.

```
package main

import (
	"fmt"

	"github.com/clbanning/mxj"
)

var data = []byte(`{"ipv4": { "address-mode": "manual", "address": { "ip": "10.10.10.10", "prefix-length": 30 }}}`)

func main() {
	m, err := mxj.NewMapJson(data)
	if err != nil {
		fmt.Println("NewMapJson err:", err)
		return
	}

	x, err := m.XmlIndent("", "  ")
	if err != nil {
		fmt.Println("XmlIndent err:", err)
	}
	fmt.Println(string(x))
}
```

Output:
```
<ipv4>
  <address>
    <ip>10.10.10.10</ip>
    <prefix-length>30</prefix-length>
  </address>
  <address-mode>manual</address-mode>
</ipv4>
```

**Comment by Slania** [comment]
@chenYunHsin-maker not sure if this might help, but Golang has some interesting interactions with JSON numbers and `Marshal`/`Unmarshal` boundaries. Are you sure you don't have some directive enabled by default or specific options enabled?

**Comment by clbanning** [comment]
I can't help you unless I have code that reproduces the problem you see.  Please post the code, or modify the code that I posted to use the clbanning/mxj calls that reproduce the problem.

**Comment by chenYunHsin-maker** [comment]
@Slania Good advise! Our team will try to find solution from this way!

**Comment by chenYunHsin-maker** [comment]
@clbanning thanks for your code without this bug, our team will try more.

**Comment by clbanning** [comment]
Note: by default the ` encoding/json` package decodes ALL numeric values as type `double`. 
```
To unmarshal JSON into an interface value, Unmarshal stores one of these in the interface value:

bool, for JSON booleans
float64, for JSON numbers
string, for JSON strings
[]interface{}, for JSON arrays
map[string]interface{}, for JSON objects
nil for JSON null
```
Source: https://golang.org/pkg/encoding/json/

**Comment by chenYunHsin-maker** [comment]
Thanks, I solved it !
