### ISSUE TITLE
invalid tag name in result from function Xml for custom data type

### ISSUE THREAD

**Issue by gqcn** [clbanning/mxj#71]
Here're the codes using version `v1.8.4` of `mxj`:
```go
package main

import (
	"fmt"
	"github.com/clbanning/mxj"
)

func main() {
	type Cdata string
	data, err := mxj.Map(map[string]interface{}{
		"data": Cdata("test"),
	}).Xml()
	if err != nil {
		panic(err)
	}
	fmt.Println(string(data))
}
```
And this outputs:
```xml
<Cdata>test</Cdata></data>
```
There's a invalid `</data>` tag in the result. What I really expects is:
```xml
<data>test</data>
```
Do I miss somthing?

**Comment by clbanning** [comment]
I'm looking into this.  Perhaps I'll have enough time tomorrow to track down how the type label is showing up in the encoding.

**Comment by gqcn** [comment]
@clbanning I have lots of unit testing cases using your package `mxj`, it is an awesome project. Thanks for your contributions, but...I think the latest commit affects the slice elements marshaling, here're the codes:
```go
package main

import (
	"fmt"
	"github.com/clbanning/mxj"
)

func main() {
	data, err := mxj.Map(map[string]interface{}{
		"data": []int{1, 2, 3},
	}).Xml()
	if err != nil {
		panic(err)
	}
	fmt.Println(string(data))
}
```
Expect XML result is:
```xml
<data><int>1</int><int>2</int><int>3</int></data>
```
But now it is 😅:
```xml
<data>[1 2 3]</data>
```

**Comment by gqcn** [comment]
@clbanning Thanks!
