### ISSUE TITLE
Parsing XML with comments gives incomplete result

### ISSUE THREAD

**Issue by neilmusgrove** [clbanning/mxj#72]
I'm trying to parse an Apache Tomcat server.xml file, make updates and save it back to a file (in exactly the same structure & layout). I've been using NewMapXmlSeq followed by SetValueForPath and then XmlSeqIndent. Broadly speaking it works, updating the value as desired but when the content is resaved a large amount of the comment content is gone. Debugging the issue it looks like the content is lost at the time of import. I've attached a file to test with but the start of the file up until the root element (<Server...) will need to be stripped before the file is parsed (to avoid the no root issue). I've not been able to identify that I'm doing anything wrong in the processing but happy to hear if that is the case. Thanks.
[server_xml.zip](https://github.com/clbanning/mxj/files/4858523/server_xml.zip)

**Comment by clbanning** [comment]
The stdlib "encoding/xml" package is stripping your leading comments.  Does the following code do what you want to do?

------------
```
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"

	"github.com/clbanning/mxj"
)

func main() {
	data, err := ioutil.ReadFile("server.xml")
	if err != nil {
		fmt.Println(err)
		return
	}

	r := bytes.NewBuffer(data)
	var i int
	for {
		// read the file a line at a time
		l, err := r.ReadBytes('\n')
		if err != nil {
			fmt.Println(err)
			return
		}
		// scan for <Server> tag - must be at SOL
		if i = bytes.Index(l, []byte("<Server>")); i != 0 {
			fmt.Print(string(l)) // or write it to a Buffer for printing later
			continue
		}

		// got the tag - build the entry from the rest of the file
		// and clean out '\n' characters
		data = append(l, r.Bytes()...)
		data = bytes.ReplaceAll(data, []byte("\n"), []byte(""))

		m, err := mxj.NewMapXmlSeq(data)
		if err != nil {
			fmt.Println(err)
			break
		}

                // here you put your m.SetValueForPath() logic

		s, err := m.XmlIndent("", "   ", "Server")
		if err != nil {
			fmt.Println(err)
			continue
		}
		fmt.Println(string(s))
	}
}
```

**Comment by neilmusgrove** [comment]
Thanks for the assistance it was helpful. I was just about to come back and say this issue can be closed since it seems to not be an issue caused by mxj
