### ISSUE TITLE
How can I disable A-Z sorting?

### ISSUE THREAD

**Issue by PanithanK** [clbanning/mxj#76]
Hi I'm trying to convert JSON to XML without A-Z sorting, Is that possible?
Thank you

**Comment by clbanning** [comment]
This package converts JSON into a ```map[string]interface{}``` value, then ranges over the map - ```_, v := range mapValue {}``` - to encode the XML.  Go does not guarantee the sequence of values returned when ranging over a map.  Thus, to ensure consistency of results, the sorting was implemented.  So, even if the values weren't sorted there'd be no guarantee that the XML values would be in the same sequence as they appear in the JSON object. 

If you've vendored or cloned the package, you can comment out lines 1029 and 1103 in```clbanning/ mxi/xml.go``` and see if that works for you

**Comment by PanithanK** [comment]
Thank you
