### ISSUE TITLE
SetValueForPath for MapSeq

### ISSUE THREAD

**Issue by amckibben** [clbanning/mxj#80]
How does one set values by path (or at all) for `MapSeq`? I see no documentation on how to do so.

https://goplay.space/#thtuDomNont

**Comment by clbanning** [comment]
I'll work on this.  Am getting some strange results with Go v1.15 with demo program for you.

**Comment by clbanning** [comment]
I'll work on this over Thanksgiving holidays.  Will have to convert my test dev environment to modules from GOPATH.

**Comment by clbanning** [comment]
Does something like this work for you?
```
package main

import (
	"fmt"

	"github.com/clbanning/mxj"
)

func main() {
	data := []byte(`
		<doc>
			<elem0>this is a test</elem0>
			<elem1>this is not a test</elem1>
			<elem2>this may be a test</elem2>
		</doc>`)

	ms, err := mxj.NewMapXmlSeq(data)
	if err != nil {
		fmt.Println("NewMapXmlSeq err:", err)
		return
	}
	val, err := ms.XmlIndent("", "   ")
	if err != nil {
		fmt.Println("XmlIndent err:", err)
		return
	}
	fmt.Printf(string(val))

	// cast to a Map value
	m := mxj.Map(ms)

	// update the 'elem2' value
	_, err = m.UpdateValuesForPath("#text:we're done with tests", "doc.elem2")
	if err != nil {
		fmt.Println("UpdateValuesForPath:", err)
		return
	}

	// marshal the MapSeq value
	// ms = mxj.MapSeq(m)
	val, err = ms.XmlIndent("", "   ")
	if err != nil {
		fmt.Println("XmlIndent err:", err)
		return
	}

	fmt.Println(string(val))
}
```

**Comment by amckibben** [comment]
Sorry @clbanning ! I missed this post until now. If I run that code I get

> XmlIndent err: invalid attribute key label: #text - due to attributes not being prefixed

on the first call to `XmlIndent()`, FYI. Not sure if you're running that on a development branch or anything.

If you're asking if the technique of casting a `MapSeq` to a `Map` in order to use the `Map` API seems reasonable or not, it seems fine to me!

**Comment by amckibben** [comment]
So if I force v2 with the import

```go
mxj "github.com/clbanning/mxj/v2"
```

then your code works fine: https://play.golang.org/p/Hqfa7ZTOoc8

outputs:

```
<doc>
   <elem0>this is a test</elem0>
   <elem1>this is not a test</elem1>
   <elem2>this may be a test</elem2>
</doc><doc>
   <elem0>this is a test</elem0>
   <elem1>this is not a test</elem1>
   <elem2>we're done with tests</elem2>
</doc>
```

**Comment by clbanning** [comment]
Yea.  I got caught by go using modules by default when I first tried to write the example.  This is a problem especially for local package libraries I've ventored to .../src/github.com/..., like where I maintain my local working copy of the github.com/clbanning/mxi package.  Now, I just set GO111MODULE=off for my dev environment, and I can work with go as I have for the last 11 years.
