### ISSUE TITLE
Map was converted to XML, incorrectly formatted

### ISSUE THREAD

**Issue by jhStrive** [clbanning/mxj#82]
version:v2.3.2
```
package main

import (
	"encoding/xml"
	"fmt"

	"github.com/clbanning/mxj/v2"
)

type result struct {
	XMLName xml.Name `xml:"xml"`
	Content string   `xml:"content"`
}

func main() {
	data, err := mxj.Map(map[string]interface{}{
		"data": result{Content: "content"},
	}).Xml()
	if err != nil {
		panic(err)
	}
	fmt.Println(string(data))
}
```
Accept result:
```
<data>{{ } content}</data>
```
The description (structures, etc.: handed to xml.Marshal()) of the func and the result is not satisfied</br>

**Comment by jhStrive** [comment]
Line 927 of xml.go causes the problem:
```
	default:
		// coerce eveything else into a string value
		value = fmt.Sprint(value)
```

**Comment by clbanning** [comment]
Are you expecting ```<data><content>content></content></data>```?

**Comment by jhStrive** [comment]
yes，I expect this result







---Original---

**Comment by jhStrive** [comment]
> Are you expecting `<data><content>content></content></data>`?
> 
> Or `<data><xml><content>content</content></xml></data>`, which is the xml.Marshal() return value from encoding `result{Content: "content"}}`?

i  expect the result which is the xml.Marshal() return ,`<data><xml><content>content</content></xml></data>`

**Comment by clbanning** [comment]
At tip.
