### ISSUE TITLE
Does mxj suppoort `cdata` tag?

### ISSUE THREAD

**Issue by bitpeng** [clbanning/mxj#83]
Suprised by your talent work. But recently I meet a question, I need the xml format like `<_update_time><![CDATA[1607282301]]></_update_time>`, but the Map.Xml() function output like this: `<_update_time>1607282301</_update_time>`. So does the mxj support `cdata` tag? Thanks.

**Comment by clbanning** [comment]
```mxj.NewMapXml``` ignores comments, directives, processing instructions, etc. - per the ```encoding/xml``` package in the stdlib.  ```mxj.NewMapXmlSeq``` tries to preserve such; however, the ```xml.Decode``` parser that is used to create ```mxj.Map``` value from source XML ignores the ```<![CDATA[...``` values in the source.  (See documentation ```note:``` for ```mxj.NewMapXmlSeq```.)

Provide me an example that creates the ```mxj.Map``` value with ```CDATA``` tag in source, and I'll take another look at it.  Perhaps, I can find a way to interrogate the ```Decoder.Token``` value and handle that as well for both decoding and encoding.

**Comment by clbanning** [comment]
Sorry.  No way to address this since we decode XML using ```encoding/xml``` package in stdlib.  See encoding/xml/xml.go, lines 692-708.
