### ISSUE TITLE
Last release not in "go get"

### ISSUE THREAD

**Issue by P1llus** [clbanning/mxj#87]
Hello @clbanning :)

Just wanted to check in to see if the latest release (v.2.4.0) will be added to the golang package management? Currently the latest released available from "go get" is 2.3.2, and defaults to that version as well.

**Comment by clbanning** [comment]
I'm not a user of modules so I'm not sure what is going on.  My ```go.mod``` file points to v2; so, I thought you should be pulling the latest version, which is v2.4.  I've made a new release with v2.4.0 just in case the missing patch digit is an issue.

**Comment by P1llus** [comment]
That fixed it @clbanning :) Much appreciated.
