### ISSUE TITLE
Map entry with nil value is serialized as <nil> causing invalid xml

### ISSUE THREAD

**Issue by nadddy** [clbanning/mxj#89]
Following code
```
func main() {
  var m1 mxj.Map
  m1 = make(map[string]interface{})
  m1["key"] = nil
  b1,_ := m1.Xml("root")
  fmt.Println(string(b1))
}
```

generates this xml:
``
<root><key><nil></key></root>
``

In previous versions (1.8.4) output was:
``
<root><key/></root>
``

Most probably this issue is caused by missing case nil in xml.go:1014
This case is handled in later switch-case at line 1240 but missing at switch-case on line 1010-1027

**Comment by clbanning** [comment]
Thanks.
