### ISSUE TITLE
Corner cases with #text

### ISSUE THREAD

**Issue by jzelinskie** [clbanning/mxj#90]
Hey there! I'm using this library for my multi-format jq tool [faq](https://github.com/faq). Thanks again for such a great library.
faq converts XML into JSON, processes it with libjq, and converts it back into XML.

A user reported an issue https://github.com/jzelinskie/faq/issues/85 which highlights two bits of surprising behavior that can be reproduced as follows:

```go
xmap, err := mxj.NewMapXml([]byte(`<p>test<span>hello</span></p>`), true)
if err != nil { panic(err) }

jsonBytes, err := xmap.Json()
if err != nil { panic(err) }

// expected: string(jsonBytes) == `{"p": {"#text": "test", "span": "hello"}}`
// got: string(jsonBytes) == `{"p": "test"}`
```

```go
jmap, err := mxj.NewMapJson(`{"p": {"#text": "test", "span": "hello" }}`)
if err != nil { panic(err) }

xmlBytes, err := jmap.Xml()
if err != nil { panic(err) }

// expected: string(xmlBytes) == `<p>text<span>hello</span></p>`
// got: panic: invalid attribute key label: #text - due to attributes not being prefixed
```

Do you think these are bugs in your parser?
I could see an argument against supporting the last example since `#text` is being synthesized.

**Comment by clbanning** [comment]
I see what might be reasonably doable.  

As noted in the README, this package was developed to manage data streams, not HTML.  So it's really not aware of style element tags, etc.

**Comment by clbanning** [comment]
v2.5.4 (at tip) address part 1.  Will get to part 2 later today or tomorrow.

**Comment by jzelinskie** [comment]
Thanks for the extremely quick updates!

>As noted in the README, this package was developed to manage data streams, not HTML. So it's really not aware of style element tags, etc.

No problem! I only used HTML as an example here -- the issue on my repo is for parsing XML documents.
